# Chapter 3

```{r}
#| include: false
library(tidyverse)
library(usethis) # use_github_file() 
library(janitor) # clean_names() 
library(skimr) # skim()

```

## Page 40

### Nations Graph

#### Activate packages

```{r}
library(usethis) # use_github_file()
library(tidyverse) # read_csv() 
library(janitor) # clean_names() 
```

#### Obtain data and save it to your computer

```{r}
#| include: false
use_github_file(repo_spec = "https://github.com/johnhoffmannVA/LinearRegression/blob/main/Nations2018.csv",
                save_as = "nations2018.csv")

nations2018 <- read_csv("nations2018.csv", show_col_types = FALSE) %>% clean_names()
```

```{r}
#| eval: false
use_github_file(repo_spec = "https://github.com/johnhoffmannVA/LinearRegression/blob/main/Nations2018.csv",
                save_as = "nations2018.csv")
```

#### Load data from your computer

```{r}
#| eval: false
nations2018 <- read_csv("nations2018.csv") %>% 
  clean_names()
```

#### Inspect data

```{r}
nations2018 %>% 
  glimpse()  
```


```{r}
#| echo: false
knitr::kable(nations2018)
```

#### Graph

```{r}
nations_plot <- ggplot(data = nations2018,
                        mapping = aes(x = perlabor,
                                      y = expend)) +
  geom_point(shape = 18) +
  geom_text(mapping = aes(label = nation),
            nudge_y = .4) +
  geom_smooth(method = "lm",
              se = FALSE,
              color = "red") +
  coord_cartesian(xlim = c(5, 65),
                  ylim = c(14, 24)) +
  scale_x_continuous(breaks = seq(5, 65, by = 10)) +
  scale_y_continuous(breaks = seq(14, 24, by = 2)) +
  labs(x = "Percent labor union",
       y = "Public expenditures",
       title = "Public Expenditures vs Percent Labor Union")

  
print(nations_plot)
```

