<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; Qualtrics – PSYC 6380 Psychological Applications of Multivariate Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./correlation.html" rel="next">
<link href="./workflow.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-2610579816e2069ae2a307bc257d5582.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./qualtrics.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Qualtrics</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">PSYC 6380 Psychological Applications of Multivariate Analysis</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">An Emphasis on Workflow</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./qualtrics.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Qualtrics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regression and correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multiple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Multiple regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mr-sample-size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sample size for multiple regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mmr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Moderated multiple regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./oneway-reg-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">One-way ANOVA via Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./twoway-reg-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Two-way ANOVA via Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#survey-response" id="toc-survey-response" class="nav-link active" data-scroll-target="#survey-response"><span class="header-section-number">2.1</span> Survey Response</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview"><span class="header-section-number">2.2</span> Overview</a></li>
  <li><a href="#required" id="toc-required" class="nav-link" data-scroll-target="#required"><span class="header-section-number">2.3</span> Required</a></li>
  <li><a href="#items-to-qualtrics" id="toc-items-to-qualtrics" class="nav-link" data-scroll-target="#items-to-qualtrics"><span class="header-section-number">2.4</span> Items to Qualtrics</a>
  <ul>
  <li><a href="#create-survey-codebook" id="toc-create-survey-codebook" class="nav-link" data-scroll-target="#create-survey-codebook"><span class="header-section-number">2.4.1</span> Create survey codebook</a>
  <ul>
  <li><a href="#block-column" id="toc-block-column" class="nav-link" data-scroll-target="#block-column"><span class="header-section-number">2.4.1.1</span> block column</a></li>
  <li><a href="#item_name-column" id="toc-item_name-column" class="nav-link" data-scroll-target="#item_name-column"><span class="header-section-number">2.4.1.2</span> item_name column</a></li>
  <li><a href="#item_text-column" id="toc-item_text-column" class="nav-link" data-scroll-target="#item_text-column"><span class="header-section-number">2.4.1.3</span> item_text column</a></li>
  <li><a href="#type-column" id="toc-type-column" class="nav-link" data-scroll-target="#type-column"><span class="header-section-number">2.4.1.4</span> type column</a></li>
  <li><a href="#response_options-column" id="toc-response_options-column" class="nav-link" data-scroll-target="#response_options-column"><span class="header-section-number">2.4.1.5</span> response_options column</a>
  <ul class="collapse">
  <li><a href="#year-of-birth" id="toc-year-of-birth" class="nav-link" data-scroll-target="#year-of-birth"><span class="header-section-number">2.4.1.5.1</span> Year of birth</a></li>
  <li><a href="#sex-3-points" id="toc-sex-3-points" class="nav-link" data-scroll-target="#sex-3-points"><span class="header-section-number">2.4.1.5.2</span> Sex 3 points</a></li>
  <li><a href="#commitment-7-points" id="toc-commitment-7-points" class="nav-link" data-scroll-target="#commitment-7-points"><span class="header-section-number">2.4.1.5.3</span> Commitment 7 points</a></li>
  <li><a href="#job-satisfaction-5-points" id="toc-job-satisfaction-5-points" class="nav-link" data-scroll-target="#job-satisfaction-5-points"><span class="header-section-number">2.4.1.5.4</span> Job Satisfaction 5 points</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#convert-to-qualtrics-format" id="toc-convert-to-qualtrics-format" class="nav-link" data-scroll-target="#convert-to-qualtrics-format"><span class="header-section-number">2.4.2</span> Convert to Qualtrics format</a>
  <ul>
  <li><a href="#create-txt-file" id="toc-create-txt-file" class="nav-link" data-scroll-target="#create-txt-file"><span class="header-section-number">2.4.2.1</span> Create TXT file</a>
  <ul class="collapse">
  <li><a href="#rstudio-on-your-computer" id="toc-rstudio-on-your-computer" class="nav-link" data-scroll-target="#rstudio-on-your-computer"><span class="header-section-number">2.4.2.1.1</span> RStudio on your computer</a></li>
  <li><a href="#rstudio-cloud" id="toc-rstudio-cloud" class="nav-link" data-scroll-target="#rstudio-cloud"><span class="header-section-number">2.4.2.1.2</span> RStudio Cloud</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#import-the-items" id="toc-import-the-items" class="nav-link" data-scroll-target="#import-the-items"><span class="header-section-number">2.4.3</span> Import the items</a>
  <ul>
  <li><a href="#begin-the-import-by-logging-into-qualtrics" id="toc-begin-the-import-by-logging-into-qualtrics" class="nav-link" data-scroll-target="#begin-the-import-by-logging-into-qualtrics"><span class="header-section-number">2.4.3.0.1</span> Begin the import by logging into Qualtrics</a></li>
  <li><a href="#click-the-create-new-project-button-in-the-top-right-of-the-page." id="toc-click-the-create-new-project-button-in-the-top-right-of-the-page." class="nav-link" data-scroll-target="#click-the-create-new-project-button-in-the-top-right-of-the-page."><span class="header-section-number">2.4.3.0.2</span> Click the Create New Project button in the top right of the page.</a></li>
  <li><a href="#under-projects-from-scratch-select-survey-by-clicking-on-it." id="toc-under-projects-from-scratch-select-survey-by-clicking-on-it." class="nav-link" data-scroll-target="#under-projects-from-scratch-select-survey-by-clicking-on-it."><span class="header-section-number">2.4.3.1</span> Under Projects from Scratch select “Survey” by clicking on it.</a></li>
  <li><a href="#click-the-get-started-button-in-the-lower-right-of-the-page." id="toc-click-the-get-started-button-in-the-lower-right-of-the-page." class="nav-link" data-scroll-target="#click-the-get-started-button-in-the-lower-right-of-the-page."><span class="header-section-number">2.4.3.2</span> Click the Get Started button in the lower right of the page.</a></li>
  <li><a href="#enter-project-name-click-create-project" id="toc-enter-project-name-click-create-project" class="nav-link" data-scroll-target="#enter-project-name-click-create-project"><span class="header-section-number">2.4.3.3</span> Enter project name, click Create Project</a></li>
  <li><a href="#use-the-tools-menu-to-import-the-items" id="toc-use-the-tools-menu-to-import-the-items" class="nav-link" data-scroll-target="#use-the-tools-menu-to-import-the-items"><span class="header-section-number">2.4.3.4</span> Use the Tools menu to import the items</a></li>
  <li><a href="#remove-the-default-empty-question-block-at-the-top-of-the-survey" id="toc-remove-the-default-empty-question-block-at-the-top-of-the-survey" class="nav-link" data-scroll-target="#remove-the-default-empty-question-block-at-the-top-of-the-survey"><span class="header-section-number">2.4.3.5</span> Remove the default Empty Question block at the top of the survey</a></li>
  </ul></li>
  <li><a href="#tweak-survey-in-qualtrics" id="toc-tweak-survey-in-qualtrics" class="nav-link" data-scroll-target="#tweak-survey-in-qualtrics"><span class="header-section-number">2.4.4</span> Tweak survey in Qualtrics</a></li>
  </ul></li>
  <li><a href="#qualtrics-data-to-r" id="toc-qualtrics-data-to-r" class="nav-link" data-scroll-target="#qualtrics-data-to-r"><span class="header-section-number">2.5</span> Qualtrics data to R</a>
  <ul>
  <li><a href="#export-from-qualtrics" id="toc-export-from-qualtrics" class="nav-link" data-scroll-target="#export-from-qualtrics"><span class="header-section-number">2.5.1</span> Export from Qualtrics</a>
  <ul>
  <li><a href="#click-the-data-analysis-tab" id="toc-click-the-data-analysis-tab" class="nav-link" data-scroll-target="#click-the-data-analysis-tab"><span class="header-section-number">2.5.1.1</span> Click the Data &amp; Analysis tab</a></li>
  <li><a href="#click-the-export-import-button" id="toc-click-the-export-import-button" class="nav-link" data-scroll-target="#click-the-export-import-button"><span class="header-section-number">2.5.1.2</span> Click the Export &amp; Import button</a></li>
  <li><a href="#click-use-choice-text" id="toc-click-use-choice-text" class="nav-link" data-scroll-target="#click-use-choice-text"><span class="header-section-number">2.5.1.3</span> Click Use Choice Text</a></li>
  </ul></li>
  <li><a href="#load-data-in-r" id="toc-load-data-in-r" class="nav-link" data-scroll-target="#load-data-in-r"><span class="header-section-number">2.5.2</span> Load data in R</a></li>
  <li><a href="#convert-to-analytic-data" id="toc-convert-to-analytic-data" class="nav-link" data-scroll-target="#convert-to-analytic-data"><span class="header-section-number">2.5.3</span> Convert to analytic data</a>
  <ul>
  <li><a href="#load-data" id="toc-load-data" class="nav-link" data-scroll-target="#load-data"><span class="header-section-number">2.5.3.1</span> Load Data</a></li>
  <li><a href="#creating-factors" id="toc-creating-factors" class="nav-link" data-scroll-target="#creating-factors"><span class="header-section-number">2.5.3.2</span> Creating factors</a>
  <ul class="collapse">
  <li><a href="#sex" id="toc-sex" class="nav-link" data-scroll-target="#sex"><span class="header-section-number">2.5.3.2.1</span> Sex</a></li>
  <li><a href="#participant-identification" id="toc-participant-identification" class="nav-link" data-scroll-target="#participant-identification"><span class="header-section-number">2.5.3.2.2</span> Participant identification</a></li>
  </ul></li>
  <li><a href="#factor-screening" id="toc-factor-screening" class="nav-link" data-scroll-target="#factor-screening"><span class="header-section-number">2.5.3.3</span> Factor screening</a></li>
  <li><a href="#numeric-screening" id="toc-numeric-screening" class="nav-link" data-scroll-target="#numeric-screening"><span class="header-section-number">2.5.3.4</span> Numeric screening</a></li>
  <li><a href="#item-values-from-labels" id="toc-item-values-from-labels" class="nav-link" data-scroll-target="#item-values-from-labels"><span class="header-section-number">2.5.3.5</span> Item values from labels</a>
  <ul class="collapse">
  <li><a href="#commitment-items" id="toc-commitment-items" class="nav-link" data-scroll-target="#commitment-items"><span class="header-section-number">2.5.3.5.1</span> Commitment Items</a></li>
  <li><a href="#job-satisfaction-conversion" id="toc-job-satisfaction-conversion" class="nav-link" data-scroll-target="#job-satisfaction-conversion"><span class="header-section-number">2.5.3.5.2</span> Job Satisfaction Conversion</a></li>
  </ul></li>
  <li><a href="#scale-scores" id="toc-scale-scores" class="nav-link" data-scroll-target="#scale-scores"><span class="header-section-number">2.5.3.6</span> Scale scores</a>
  <ul class="collapse">
  <li><a href="#reverse-key-items" id="toc-reverse-key-items" class="nav-link" data-scroll-target="#reverse-key-items"><span class="header-section-number">2.5.3.6.1</span> Reverse-key items</a></li>
  <li><a href="#creating-scores" id="toc-creating-scores" class="nav-link" data-scroll-target="#creating-scores"><span class="header-section-number">2.5.3.6.2</span> Creating scores</a></li>
  <li><a href="#removing-fast-responders" id="toc-removing-fast-responders" class="nav-link" data-scroll-target="#removing-fast-responders"><span class="header-section-number">2.5.3.6.3</span> Removing fast responders</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#complete-script" id="toc-complete-script" class="nav-link" data-scroll-target="#complete-script"><span class="header-section-number">2.5.4</span> Complete script</a></li>
  </ul></li>
  <li><a href="#extra-help" id="toc-extra-help" class="nav-link" data-scroll-target="#extra-help"><span class="header-section-number">2.6</span> Extra Help</a>
  <ul>
  <li><a href="#qualtrics" id="toc-qualtrics" class="nav-link" data-scroll-target="#qualtrics"><span class="header-section-number">2.6.1</span> Qualtrics</a></li>
  <li><a href="#surveys" id="toc-surveys" class="nav-link" data-scroll-target="#surveys"><span class="header-section-number">2.6.2</span> Surveys</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Qualtrics</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="survey-response" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="survey-response"><span class="header-section-number">2.1</span> Survey Response</h2>
<p>Designing a survey process in way that ensure a high response rate is crucial to obtaining quality data. A low response rate can be problematic for many reasons. I encourage you to check out the resource below to help you design a survey process that maximizes your response rate.</p>
<p><a href="https://a.co/d/fjk0WEG">Internet, Phone, Mail, and Mixed-Mode Surveys: The Tailored Design Method</a></p>
</section>
<section id="overview" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="overview"><span class="header-section-number">2.2</span> Overview</h2>
<p>There are two tasks covered in this chapter: <strong>1)</strong> importing surveys into Qualtrics and <strong>2)</strong> moving data from Qualtrics to R. An overview of each process is below.</p>
<p><strong>1. Importing items into Qualtrics</strong></p>
<ul>
<li>Create a survey codebook in Excel (or similar program) that has each item and the response options for it</li>
<li>Convert the survey codebook to Qualtrics <a href="https://www.qualtrics.com/support/survey-platform/survey-module/survey-tools/import-and-export-surveys/">Advanced Text Format</a></li>
<li>Import the items</li>
<li>Tweak the survey after import</li>
</ul>
<p><strong>2. Qualtrics Data to R</strong></p>
<ul>
<li>Export the raw data from Qualtrics with maximal information in the data file</li>
<li>Load the raw data into R</li>
<li>Convert the raw data to analytic data. This conversion includes: assigning values to response options (e.g., “Strongly Disagree” to a numeric value), flipping response for reverse-worded (i.e., reverse-keyed) items, and creating scale scores.</li>
</ul>
<p>The overall steps are quite simple and I walk you through each step in detail below.</p>
</section>
<section id="required" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="required"><span class="header-section-number">2.3</span> Required</h2>
<p>The files below are used in this chapter. Right click to save each file.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Relevant files</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="survey_codebook.csv">survey_codebook.csv</a></td>
</tr>
<tr class="even">
<td><a href="items_qualtrics_format.txt">items_qualtrics_format.txt</a></td>
</tr>
<tr class="odd">
<td><a href="data_qualtrics.csv">data_qualtrics.csv</a></td>
</tr>
<tr class="even">
<td><a href="script_qualtrics.R">script_qualtrics.R</a></td>
</tr>
</tbody>
</table>
<p>The following CRAN packages must be installed:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Required CRAN Packages</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>tidyverse</td>
</tr>
<tr class="even">
<td>janitor</td>
</tr>
<tr class="odd">
<td>remotes</td>
</tr>
</tbody>
</table>
<p>The following GitHub packages must be installed:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Required GitHub Packages</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="https://github.com/dstanley4/qualtricsMaker">dstanley4/qualtricsMaker</a></td>
</tr>
</tbody>
</table>
<p>A GitHub package can be installed using the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">"dstanley4/qualtricsMaker"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="items-to-qualtrics" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="items-to-qualtrics"><span class="header-section-number">2.4</span> Items to Qualtrics</h2>
<p>There are two approaches to entering survey items into Qualtrics.</p>
<ul>
<li><p>Enter the items one at a time using the Qualtrics web interface.</p></li>
<li><p>Create a text file in the Qualtrics <a href="https://www.qualtrics.com/support/survey-platform/survey-module/survey-tools/import-and-export-surveys/">Advanced Text Format</a> and import the items. Be warned though a bit of tweaking is often still needed using the web interface.</p></li>
</ul>
<p>Here we focus only on the second approach to entering items into Qualtrics.</p>
<section id="create-survey-codebook" class="level3" data-number="2.4.1">
<h3 data-number="2.4.1" class="anchored" data-anchor-id="create-survey-codebook"><span class="header-section-number">2.4.1</span> Create survey codebook</h3>
<p>The easy way to create items in the <a href="https://www.qualtrics.com/support/survey-platform/survey-module/survey-tools/import-and-export-surveys/">Advanced Text Format</a> is to use the qualtricsMaker package. With this package you create a spreadsheet with the items and then convert that spreadsheet to the Advanced Text Format.</p>
<p>Consider a scenario where we want to create a survey that contains 2 demographics items, 18 commitment items, and 4 job satisfaction items. The <em>three-component model of commitment</em> items are from <span class="citation" data-cites="meyer1993commitment">(<a href="references.html#ref-meyer1993commitment" role="doc-biblioref">Meyer, Allen, and Smith 1993</a>)</span> and the <em>job satisfaction</em> items are from <span class="citation" data-cites="thompson2012brief">(<a href="references.html#ref-thompson2012brief" role="doc-biblioref">Thompson and Phua 2012</a>)</span>.</p>
<p>We begin by creating a survey codebook spreadsheet in Excel (or similar program). The spreadsheet should have the columns with the names: block, item_name, item_text, type, response_options. The completed file ( <a href="survey_codebook.csv">survey_codebook.csv</a>) is illustrated below. I provide a detailed description of what should be placed in each column after the figure. Remember to work from the guiding principle that one row is used for one item/question.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_items.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<section id="block-column" class="level4" data-number="2.4.1.1">
<h4 data-number="2.4.1.1" class="anchored" data-anchor-id="block-column"><span class="header-section-number">2.4.1.1</span> block column</h4>
<p>Enter any text you wish to use as a label for a block of items.</p>
</section>
<section id="item_name-column" class="level4" data-number="2.4.1.2">
<h4 data-number="2.4.1.2" class="anchored" data-anchor-id="item_name-column"><span class="header-section-number">2.4.1.2</span> item_name column</h4>
<p>To make your life easier down the road, it is critical you set up your spreadsheet or online survey such that it uses a naming convention prior to data collection. Recall the <a href="https://dstanley4.github.io/psyc6060bookdown/an-emphasis-on-workflow.html#naming-conventions">naming convention from the previous chapter</a>.</p>
</section>
<section id="item_text-column" class="level4" data-number="2.4.1.3">
<h4 data-number="2.4.1.3" class="anchored" data-anchor-id="item_text-column"><span class="header-section-number">2.4.1.3</span> item_text column</h4>
<p>The item_text column contains the text for each item. Note that if you use commas in your item text do not save this file as a .csv file - it will not work. Rather save it as .tsv file (tab separated values). Then use read_tsv command instead of the read_csv command in the code that follows later.</p>
</section>
<section id="type-column" class="level4" data-number="2.4.1.4">
<h4 data-number="2.4.1.4" class="anchored" data-anchor-id="type-column"><span class="header-section-number">2.4.1.4</span> type column</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 31%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Code for type column</th>
<th>Qualtrics Item Type</th>
<th>Additional Information</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>matrix</td>
<td>matrix</td>
<td>If the first item in a block has type <em>matrix</em> all items in the block will be used to construct the matrix question. <strong>Unfortunately, importing item_names for matrix questions is not supported by Qualtrics. You will need to manually restore your item_names following the directions below for matrix items.</strong></td>
</tr>
<tr class="even">
<td>MC</td>
<td>multiple choice vertical format</td>
<td></td>
</tr>
<tr class="odd">
<td>MC_horizontal</td>
<td>multiple choice horizontal format</td>
<td></td>
</tr>
<tr class="even">
<td>MC_multi_horizontal</td>
<td>multiple choice horizontal format multiple answers</td>
<td></td>
</tr>
<tr class="odd">
<td>MC_select</td>
<td>select box</td>
<td></td>
</tr>
<tr class="even">
<td>MC_multi_select</td>
<td>select multiple boxes</td>
<td></td>
</tr>
<tr class="odd">
<td>MC_dropdown</td>
<td>dropdown</td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="response_options-column" class="level4" data-number="2.4.1.5">
<h4 data-number="2.4.1.5" class="anchored" data-anchor-id="response_options-column"><span class="header-section-number">2.4.1.5</span> response_options column</h4>
<p>The Likert items for the different blocks use different response options. The commitment items use a 7-point response option whereas the job satisfaction items use a 5-point response option.</p>
<section id="year-of-birth" class="level5" data-number="2.4.1.5.1">
<h5 data-number="2.4.1.5.1" class="anchored" data-anchor-id="year-of-birth"><span class="header-section-number">2.4.1.5.1</span> Year of birth</h5>
<p>We used a number of response options to indicate Year of Birth. We entered them as per below. Each response option is separated by a semi-colon. Each of the years below will be in the dropdown button.</p>
<p><strong>Entered in the response_option column as below. Each option separated by a semicolon.</strong></p>
<p>1940;1941;1942;1943;1944;1945;1946;1947;1948;1949;1950;1951;1952;1953;1954;1955;1956;1957;1958;1959;1960;1961;1962;1963;1964;1965;1966;1967;1968;1969;1970;1971;1972;1973;1974;1975;1976;1977;1978;1979;1980;1981;1982;1983;1984;1985;1986;1987;1988;1989;1990;1991;1992;1993;1994;1995;1996;1997;1998;1999;2000;2001;2002;2003;2004;2005;2006;2007;2008;2009;2010</p>
</section>
<section id="sex-3-points" class="level5" data-number="2.4.1.5.2">
<h5 data-number="2.4.1.5.2" class="anchored" data-anchor-id="sex-3-points"><span class="header-section-number">2.4.1.5.2</span> Sex 3 points</h5>
<p>Please note that in psychology we distinguish between sex and gender. We use the term “sex” to refer to underlying biology. In contrast, we use the term “gender” to refer a psychological construct (i.e., gender identity). A person’s sex and gender may be quite different. Depending on the theory used in a study, you might be interested in sex or gender or both. In this example, we are using sex but not gender. If you were asking about gender - you would have a much longer (and quite different) list of options.</p>
<p><strong>Entered in the response_option column as below. Each option separated by a semicolon.</strong></p>
<p>male; female; intersex</p>
</section>
<section id="commitment-7-points" class="level5" data-number="2.4.1.5.3">
<h5 data-number="2.4.1.5.3" class="anchored" data-anchor-id="commitment-7-points"><span class="header-section-number">2.4.1.5.3</span> Commitment 7 points</h5>
<p><strong>Entered in the response_option column as below. Each option separated by a semicolon.</strong></p>
<p>Strongly Disagree;Moderately Disagree;Slightly Disagree;Neither Agree nor Disagree;Slightly Agree;Moderately Agree;Strongly Agree</p>
</section>
<section id="job-satisfaction-5-points" class="level5" data-number="2.4.1.5.4">
<h5 data-number="2.4.1.5.4" class="anchored" data-anchor-id="job-satisfaction-5-points"><span class="header-section-number">2.4.1.5.4</span> Job Satisfaction 5 points</h5>
<p><strong>Entered in the response_option column as below. Each option separated by a semicolon.</strong></p>
<p>Strongly Disagree; Disagree; Neutral; Agree; Strongly Agree</p>
</section>
</section>
</section>
<section id="convert-to-qualtrics-format" class="level3" data-number="2.4.2">
<h3 data-number="2.4.2" class="anchored" data-anchor-id="convert-to-qualtrics-format"><span class="header-section-number">2.4.2</span> Convert to Qualtrics format</h3>
<section id="create-txt-file" class="level4" data-number="2.4.2.1">
<h4 data-number="2.4.2.1" class="anchored" data-anchor-id="create-txt-file"><span class="header-section-number">2.4.2.1</span> Create TXT file</h4>
<p>Once you have the survey codebook above, you need to convert it to an <a href="https://www.qualtrics.com/support/survey-platform/survey-module/survey-tools/import-and-export-surveys/">Advanced Text Format</a> .txt file. We can do so by following the steps below. The instructions differ slightly for RStudio Cloud and RStudio - both are presented.</p>
<section id="rstudio-on-your-computer" class="level5" data-number="2.4.2.1.1">
<h5 data-number="2.4.2.1.1" class="anchored" data-anchor-id="rstudio-on-your-computer"><span class="header-section-number">2.4.2.1.1</span> RStudio on your computer</h5>
<ol type="1">
<li><p>Create a folder on your computer called “new_survey” <strong>with the survey_codebook.csv file in it.</strong></p></li>
<li><p>Open RStudio. Then go to File &gt; New Project… and select Existing Directory.</p></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_existing_dir.png" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
<ol start="2" type="1">
<li>Then find and select the “new_survey” folder on your hard drive and click the Create Project button.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_folder.png" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
<ol start="3" type="1">
<li>You should previously have installed the <em>remotes</em> and <em>tidyverse</em> packages from the CRAN and the qualtricsMaker package from GitHub. If you haven’t done this already type the commands below into the <strong>Console</strong>.</li>
</ol>
<p><strong>Installing Packages from the CRAN</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"tidyverse"</span>, <span class="at">dep =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"remotes"</span>, <span class="at">dep =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Installing Package from GitHub</strong></p>
<p>Then install the qualtricsMaker package from GitHub:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">"dstanley4/qualtricsMaker"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ol start="3" type="1">
<li>Create a new script by going to File &gt; New File &gt; R Script. A new script will appear in RStudio. Immediately press Control-S to save the script. Call it “script_convert.R”.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_new_script.png" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
<ol start="4" type="1">
<li>Place the code below into the script and press Control-S to save your work.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(qualtricsMaker)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>survey_codebook <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"survey_codebook.csv"</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">make_survey</span>(survey_codebook,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">filename =</span> <span class="st">"items_qualtrics_format.txt"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ol start="5" type="1">
<li>Run the script by pressing the Source button in the top right of the the Script window. Doing so will create the items_qualtrics_format.txt file that you will import into Qualtrics. You can see the file after it has been created in the Files tab below.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_post_creation.png" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
<p><strong>Congratulations - your items are ready to be imported into Qualtrics. Move on to the “Import the items” section.</strong></p>
</section>
<section id="rstudio-cloud" class="level5" data-number="2.4.2.1.2">
<h5 data-number="2.4.2.1.2" class="anchored" data-anchor-id="rstudio-cloud"><span class="header-section-number">2.4.2.1.2</span> RStudio Cloud</h5>
<ol type="1">
<li><p>Open a new project in RStudio Cloud</p></li>
<li><p>You should previously have installed the remote and tidyverse package from the CRAN and the qualtricsMaker package from GitHub. If you haven’t done this already type the commands below into the <strong>Console</strong>.However, if you are working from a class project I created <strong>these packages will have been installed already for you.</strong></p></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"tidyverse"</span>, <span class="at">dep =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"remotes"</span>, <span class="at">dep =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Then install the qualtricsMaker package from GitHub:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">"dstanley4/qualtricsMaker"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ol start="4" type="1">
<li>Import the <a href="survey_codebook.csv">survey_codebook.csv</a> file by using the Upload button in the Files tab in the lower right panel.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_import_button.png" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
<ol start="5" type="1">
<li>Click the Choose File button and select the survey_codebook.csv file on your hard drive. Then click OK. The survey_codebook.csv file will then appear on the Files tab within RStudio Cloud.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_choose_file.png" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
<ol start="6" type="1">
<li>Create a new script by going to File &gt; New File &gt; R Script. A new script will appear in RStudio. Immediately press Control-S to save the script. Call it “script_convert.R”.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_new_script_RSC.png" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
<ol start="7" type="1">
<li>Place the code below into the script and press Control-S to save your work.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(qualtricsMaker)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>survey_codebook <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"survey_codebook.csv"</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="fu">make_survey</span>(survey_codebook,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">filename =</span> <span class="st">"items_qualtrics_format.txt"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ol start="8" type="1">
<li>Run the script by pressing the Source button in the top right of the the Script window. Doing so will create the items_qualtrics_format.txt file that you will import into Qualtrics. You can see the file after it has been created in the Files tab below.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_post_creation_RSC.png" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
<ol start="9" type="1">
<li>Select the checkbox beside the file you just created: items_qualtrics_format.txt</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_select_export_file.png" class="img-fluid figure-img" style="width:35.0%"></p>
</figure>
</div>
</div>
</div>
<ol start="10" type="1">
<li>Select Export from the More menu.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_select_export_menu.png" class="img-fluid figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
<ol start="11" type="1">
<li>Leave the filename as it appears and click the Download button. The file will appear in the Downloads directory on your computer.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_export_filename.png" class="img-fluid figure-img" style="width:40.0%"></p>
</figure>
</div>
</div>
</div>
<ol start="12" type="1">
<li>Move the file (items_qualtrics_format.txt) from the Download folder to an easy to access place (e.g.&nbsp;the Desktop).</li>
</ol>
<p><strong>Congratulation - your items are ready to be imported into Qualtrics. Move on to the “Import the items” section.</strong></p>
</section>
</section>
</section>
<section id="import-the-items" class="level3" data-number="2.4.3">
<h3 data-number="2.4.3" class="anchored" data-anchor-id="import-the-items"><span class="header-section-number">2.4.3</span> Import the items</h3>
<p>In the previous step you created items_qualtrics_format.txt. This file is illustrated below - well the middle of the file is illustrated below. You can think of the file created by the survey_maker command above as a starting point. You could open up this file in a text editor and make further modifications or additions based on learning the <a href="https://www.qualtrics.com/support/survey-platform/survey-module/survey-tools/import-and-export-surveys/">Advanced Text Format</a>. For example, you might not want the matrix items to be in their own block. If so, you would simply remove the block text [[Block:Commitment]] from the text file prior to following the directions below. If you’re a Mac user you might find the text editor <a href="https://www.barebones.com/products/bbedit/download.html">BBEdit</a> helpful for this purpose – the free version is sufficient. After you download BBEdit you have access to all of its features. Once the free trial ends - the core features are still free. You only need to purchase it if you want the advanced features (and you won’t need the advanced features).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_advanced_text.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<section id="begin-the-import-by-logging-into-qualtrics" class="level5" data-number="2.4.3.0.1">
<h5 data-number="2.4.3.0.1" class="anchored" data-anchor-id="begin-the-import-by-logging-into-qualtrics"><span class="header-section-number">2.4.3.0.1</span> Begin the import by logging into Qualtrics</h5>
<p>Begin by logging into Qualtrics via the University of Guelph site for <a href="https://www.lib.uoguelph.ca/working-data/data-collection-surveys">Data Collection &amp; Surveys</a>. After you log in, continue below.</p>
</section>
<section id="click-the-create-new-project-button-in-the-top-right-of-the-page." class="level5" data-number="2.4.3.0.2">
<h5 data-number="2.4.3.0.2" class="anchored" data-anchor-id="click-the-create-new-project-button-in-the-top-right-of-the-page."><span class="header-section-number">2.4.3.0.2</span> Click the Create New Project button in the top right of the page.</h5>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_b1.png" class="img-fluid figure-img" style="width:20.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="under-projects-from-scratch-select-survey-by-clicking-on-it." class="level4" data-number="2.4.3.1">
<h4 data-number="2.4.3.1" class="anchored" data-anchor-id="under-projects-from-scratch-select-survey-by-clicking-on-it."><span class="header-section-number">2.4.3.1</span> Under Projects from Scratch select “Survey” by clicking on it.</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_b2.png" class="img-fluid figure-img" style="width:30.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="click-the-get-started-button-in-the-lower-right-of-the-page." class="level4" data-number="2.4.3.2">
<h4 data-number="2.4.3.2" class="anchored" data-anchor-id="click-the-get-started-button-in-the-lower-right-of-the-page."><span class="header-section-number">2.4.3.2</span> Click the Get Started button in the lower right of the page.</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_b3.png" class="img-fluid figure-img" style="width:40.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="enter-project-name-click-create-project" class="level4" data-number="2.4.3.3">
<h4 data-number="2.4.3.3" class="anchored" data-anchor-id="enter-project-name-click-create-project"><span class="header-section-number">2.4.3.3</span> Enter project name, click Create Project</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_b4.png" class="img-fluid figure-img" style="width:40.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="use-the-tools-menu-to-import-the-items" class="level4" data-number="2.4.3.4">
<h4 data-number="2.4.3.4" class="anchored" data-anchor-id="use-the-tools-menu-to-import-the-items"><span class="header-section-number">2.4.3.4</span> Use the Tools menu to import the items</h4>
<p>Select the Import option and then specify the filename (items_qualtrics_format.txt) for the Advanced Text import file with the items in it.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_b5.png" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
<p><strong>Congratulation - your items have been imported into Qualtrics.</strong></p>
</section>
<section id="remove-the-default-empty-question-block-at-the-top-of-the-survey" class="level4" data-number="2.4.3.5">
<h4 data-number="2.4.3.5" class="anchored" data-anchor-id="remove-the-default-empty-question-block-at-the-top-of-the-survey"><span class="header-section-number">2.4.3.5</span> Remove the default Empty Question block at the top of the survey</h4>
<p>Scroll to the top of the survey and you will see a Default Question Block above your first block. Click on the three dots “…” in the top right of this block and select Delete to remove it.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_empty_block.png" class="img-fluid figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="tweak-survey-in-qualtrics" class="level3" data-number="2.4.4">
<h3 data-number="2.4.4" class="anchored" data-anchor-id="tweak-survey-in-qualtrics"><span class="header-section-number">2.4.4</span> Tweak survey in Qualtrics</h3>
<p>Now you need to tweak the survey using the Qualtrics interface. Recall that when you import items into Qualtrics, matrix-style questions will loose their item names. <strong>You need to manually restore the item names for matrix questions now.</strong></p>
<ol type="1">
<li>Begin by scrolling down to a block of matrix-style questions. Select the block so it gets a blue rectangle around it.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_exporttag_select.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ol start="2" type="1">
<li>On the left side menu go the “Question Behaviour” menu and select “Recode values”</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_exporttag_menu.png" class="img-fluid figure-img" style="width:30.0%"></p>
</figure>
</div>
</div>
</div>
<ol start="3" type="1">
<li>Click the Export Question Tags check box. You will see the default names for the items (instead of the ones you indicated in the codebook). Click the Close button in the lower right when you’re done.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_exporttag_defaults.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ol start="4" type="1">
<li>Manually restore the item names from the survey codebook by clicking the blue name for each item and fixing it. Don’t forget to use proper item naming formats and include the reverse-key status of each item.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_exporttag_defaults_fixed.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ol start="5" type="1">
<li>Collect your data!</li>
</ol>
</section>
</section>
<section id="qualtrics-data-to-r" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="qualtrics-data-to-r"><span class="header-section-number">2.5</span> Qualtrics data to R</h2>
<p>Following data collection, you can obtain your data from Qualtrics. As of 2021, Tri-Agency (NSERC, SSHRC, CIHR) <a href="https://www.science.gc.ca/eic/site/063.nsf/eng/h_97610.html">policy</a> is that data collected with Tri-Agency funded research must be available for reuse by others. The data should follow the FAIR (Findable, Accessible, Interoperable, and Reusable) principle. Consequently, when you export the data from Qualtrics (and eventually post it) we want to ensure it has as much information in it as possible. This principle guides the options we select below.</p>
<section id="export-from-qualtrics" class="level3" data-number="2.5.1">
<h3 data-number="2.5.1" class="anchored" data-anchor-id="export-from-qualtrics"><span class="header-section-number">2.5.1</span> Export from Qualtrics</h3>
<section id="click-the-data-analysis-tab" class="level4" data-number="2.5.1.1">
<h4 data-number="2.5.1.1" class="anchored" data-anchor-id="click-the-data-analysis-tab"><span class="header-section-number">2.5.1.1</span> Click the Data &amp; Analysis tab</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_data.png" class="img-fluid figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="click-the-export-import-button" class="level4" data-number="2.5.1.2">
<h4 data-number="2.5.1.2" class="anchored" data-anchor-id="click-the-export-import-button"><span class="header-section-number">2.5.1.2</span> Click the Export &amp; Import button</h4>
<p>Then click the <strong>Export Data…</strong> option.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_export.png" class="img-fluid figure-img" style="width:20.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="click-use-choice-text" class="level4" data-number="2.5.1.3">
<h4 data-number="2.5.1.3" class="anchored" data-anchor-id="click-use-choice-text"><span class="header-section-number">2.5.1.3</span> Click Use Choice Text</h4>
<p>To ensure the data can be used by others, as per the FAIR policy described above, we SELECT the “Use Choice Text” option when exporting data. If you were to (non-optimally) select “Use numeric value” as an export option then the resulting data file would be missing information that make it difficult for others to use. Then click the Download button.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_export_choice.png" class="img-fluid figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
<p>The file will appear in your downloads directory.</p>
<ul>
<li><p>It will likely be a zipped filed. Unzip the file before proceeding. On a Mac, you can just double click the file to do so.</p></li>
<li><p>Rename the file to data_qualtrics.csv</p></li>
</ul>
</section>
</section>
<section id="load-data-in-r" class="level3" data-number="2.5.2">
<h3 data-number="2.5.2" class="anchored" data-anchor-id="load-data-in-r"><span class="header-section-number">2.5.2</span> Load data in R</h3>
<p>To load the data in R follow the steps below</p>
<ol type="1">
<li><p>Create a new folder called “survey_data”</p></li>
<li><p>Drag the data_qualtrics.csv file to the survey_data folder.</p></li>
<li><p>Use the steps described previously on this page, use RStudio to create project for this data.</p></li>
<li><p>You may be tempted to load the data using the usual read_csv() process. This will be problematic due to the way the data is formatted in the .csv file. (see image below.)</p></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_qualtrics/images/screenshot_raw_data.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<ol start="5" type="1">
<li>You can see by inspecting the data screenshot above that a variety of columns have been included before our first data column (year_of_birth) which appears on the far right of screenshot. Also note that there are three header rows at the top of the file before the data which starts on row 4. So there are few problems that need to be addressed when we load data from Qualtrics.</li>
</ol>
<ul>
<li><p>Obtain the names from the first header row but read the data from row 4 on.</p></li>
<li><p>Remove some, or all, of the additional columns on the left side of data set added by Qualtrics</p></li>
<li><p>Ensure our variable names follow the tidyverse <a href="https://style.tidyverse.org">style guide</a></p></li>
<li><p>Ensure we DO NOT modify the data_qualtrics.csv file in Excel or other program. That would destroy the reproducibility of our work in the very first step.</p></li>
</ul>
</section>
<section id="convert-to-analytic-data" class="level3" data-number="2.5.3">
<h3 data-number="2.5.3" class="anchored" data-anchor-id="convert-to-analytic-data"><span class="header-section-number">2.5.3</span> Convert to analytic data</h3>
<p>The issues described above are all solved with the script below.</p>
<p>Additionally, in the script we also:</p>
<ul>
<li><p>Convert categorical variable to factors</p></li>
<li><p>Screen both numeric variables and factors for impossible values</p></li>
<li><p>Convert Likert items from labels (e.g., “Strongly Disagree”) to numbers (e.g., 1)</p></li>
<li><p>Flip reverse-key (i.e., reverse worded items) so they are scored in the right direction</p></li>
<li><p>Combine items (e.g., aff_com1_likert7) for the same measure into a single scale score (e.g., affective_commitment)</p></li>
<li><p>Remove item columns (e.g., aff_com1_likert7) after that have been combined into the scale score while retaining the scale score column column (e.g., affective_commitment)</p></li>
</ul>
<section id="load-data" class="level4" data-number="2.5.3.1">
<h4 data-number="2.5.3.1" class="anchored" data-anchor-id="load-data"><span class="header-section-number">2.5.3.1</span> Load Data</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Date: YYYY-MM-DD</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Name: your name here</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Example: Single occasion survey</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="co"># read the file in the normal way and get just the names of the columns.</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="co"># put the names into the col_names</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>survey_file <span class="ot">&lt;-</span> <span class="st">"data_qualtrics.csv"</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>col_names <span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">read_csv</span>(survey_file,</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>                            <span class="at">n_max =</span> <span class="dv">0</span>,</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>                            <span class="at">show_col_types =</span> <span class="cn">FALSE</span>))</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a><span class="co"># skip the first 3 rows than read in the data and use names from above</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>raw_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(survey_file,</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>                  <span class="at">col_names =</span> col_names, </span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>                  <span class="at">skip =</span> <span class="dv">3</span>,</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>                  <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Remove the Qualtrics columns you probably don’t want:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Qualtrics columns to remove (any_of() ignores names not present)</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>cols_to_remove <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"StartDate"</span>,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"EndDate"</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Status"</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"IPAddress"</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Progress"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Finished"</span>,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"RecordedDate"</span>,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"ResponseId"</span>,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"RecipientLastName"</span>,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"RecipientFirstName"</span>,</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"RecipientEmail"</span>,</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"ExternalReference"</span>,</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"LocationLatitude"</span>,</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"LocationLongitude"</span>,</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"DistributionChannel"</span>,</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"UserLanguage"</span>)</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a><span class="co"># remove the unwanted Qualtrics columns</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>raw_data <span class="ot">&lt;-</span> raw_data <span class="sc">|&gt;</span> </span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">!</span><span class="fu">any_of</span>(cols_to_remove))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We make a copy of the data called analytic_data_survey since the goals of the next several steps are to prepare the data for analysis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> raw_data</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>In the command below, we ensure our column names follow the tidyverse <a href="https://style.tidyverse.org">style guide</a> by using the clean_names() command from the janitor package. Additionally, we remove empty row and columns from the data using the remove_empty_cols() and remove_empty_rows(), respectively.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Initial cleaning</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Convert column names to tidyverse style guide</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Remove empty rows and columns</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">remove_empty</span>(<span class="st">"rows"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">remove_empty</span>(<span class="st">"cols"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>You can confirm the column names following our naming convention with the glimpse command - and see the data type for each column.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(analytic_data_survey)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 150
Columns: 25
$ duration_in_seconds  &lt;dbl&gt; 244, 134, 237, 110, 151, 92, 393, 165, 315, 262, …
$ year_of_birth        &lt;dbl&gt; 1961, 2006, 2008, 1985, 1953, 1957, 1998, 1970, 1…
$ sex                  &lt;chr&gt; "female", "female", "female", "male", "intersex",…
$ aff_com1_likert7     &lt;chr&gt; "Slightly Agree", "Neither Agree nor Disagree", "…
$ aff_com2_likert7     &lt;chr&gt; "Slightly Agree", "Slightly Disagree", "Neither A…
$ aff_com3_likert7rev  &lt;chr&gt; "Strongly Disagree", "Neither Agree nor Disagree"…
$ aff_com4_likert7rev  &lt;chr&gt; "Moderately Disagree", "Strongly Agree", "Moderat…
$ aff_com5_likert7rev  &lt;chr&gt; "Strongly Disagree", "Neither Agree nor Disagree"…
$ aff_com6_likert7     &lt;chr&gt; "Moderately Agree", "Strongly Agree", "Strongly D…
$ contin_com1_likert7  &lt;chr&gt; "Strongly Agree", "Neither Agree nor Disagree", "…
$ contin_com2_likert7  &lt;chr&gt; "Slightly Agree", "Slightly Agree", "Slightly Dis…
$ contin_com3_likert7  &lt;chr&gt; "Strongly Disagree", "Slightly Disagree", "Strong…
$ contin_com4_likert7  &lt;chr&gt; "Moderately Agree", "Neither Agree nor Disagree",…
$ contin_com5_likert7  &lt;chr&gt; "Slightly Agree", "Slightly Agree", "Strongly Dis…
$ contin_com6_likert7  &lt;chr&gt; "Moderately Disagree", "Moderately Disagree", "St…
$ norm_com1_likert7rev &lt;chr&gt; "Neither Agree nor Disagree", "Slightly Disagree"…
$ norm_com2_likert7    &lt;chr&gt; "Moderately Disagree", "Moderately Agree", "Stron…
$ norm_com3_likert7    &lt;chr&gt; "Neither Agree nor Disagree", "Neither Agree nor …
$ norm_com4_likert7    &lt;chr&gt; "Moderately Disagree", "Moderately Disagree", "St…
$ norm_com5_likert7    &lt;chr&gt; "Strongly Disagree", "Strongly Disagree", "Strong…
$ norm_com6_likert7    &lt;chr&gt; "Strongly Agree", "Strongly Disagree", "Moderatel…
$ job_aff1_likert5     &lt;chr&gt; "Strongly Agree", "Strongly Agree", "Neutral", "S…
$ job_aff2_likert5     &lt;chr&gt; "Strongly Disagree", "Strongly Agree", "Strongly …
$ job_aff3_likert5     &lt;chr&gt; "Neutral", "Strongly Disagree", "Disagree", "Stro…
$ job_aff4_likert5     &lt;chr&gt; "Disagree", "Strongly Agree", "Agree", "Strongly …</code></pre>
</div>
</div>
</section>
<section id="creating-factors" class="level4" data-number="2.5.3.2">
<h4 data-number="2.5.3.2" class="anchored" data-anchor-id="creating-factors"><span class="header-section-number">2.5.3.2</span> Creating factors</h4>
<p>Following initial cleaning, we identify categorical variables as factors.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(analytic_data_survey)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 150
Columns: 25
$ duration_in_seconds  &lt;dbl&gt; 244, 134, 237, 110, 151, 92, 393, 165, 315, 262, …
$ year_of_birth        &lt;dbl&gt; 1961, 2006, 2008, 1985, 1953, 1957, 1998, 1970, 1…
$ sex                  &lt;chr&gt; "female", "female", "female", "male", "intersex",…
$ aff_com1_likert7     &lt;chr&gt; "Slightly Agree", "Neither Agree nor Disagree", "…
$ aff_com2_likert7     &lt;chr&gt; "Slightly Agree", "Slightly Disagree", "Neither A…
$ aff_com3_likert7rev  &lt;chr&gt; "Strongly Disagree", "Neither Agree nor Disagree"…
$ aff_com4_likert7rev  &lt;chr&gt; "Moderately Disagree", "Strongly Agree", "Moderat…
$ aff_com5_likert7rev  &lt;chr&gt; "Strongly Disagree", "Neither Agree nor Disagree"…
$ aff_com6_likert7     &lt;chr&gt; "Moderately Agree", "Strongly Agree", "Strongly D…
$ contin_com1_likert7  &lt;chr&gt; "Strongly Agree", "Neither Agree nor Disagree", "…
$ contin_com2_likert7  &lt;chr&gt; "Slightly Agree", "Slightly Agree", "Slightly Dis…
$ contin_com3_likert7  &lt;chr&gt; "Strongly Disagree", "Slightly Disagree", "Strong…
$ contin_com4_likert7  &lt;chr&gt; "Moderately Agree", "Neither Agree nor Disagree",…
$ contin_com5_likert7  &lt;chr&gt; "Slightly Agree", "Slightly Agree", "Strongly Dis…
$ contin_com6_likert7  &lt;chr&gt; "Moderately Disagree", "Moderately Disagree", "St…
$ norm_com1_likert7rev &lt;chr&gt; "Neither Agree nor Disagree", "Slightly Disagree"…
$ norm_com2_likert7    &lt;chr&gt; "Moderately Disagree", "Moderately Agree", "Stron…
$ norm_com3_likert7    &lt;chr&gt; "Neither Agree nor Disagree", "Neither Agree nor …
$ norm_com4_likert7    &lt;chr&gt; "Moderately Disagree", "Moderately Disagree", "St…
$ norm_com5_likert7    &lt;chr&gt; "Strongly Disagree", "Strongly Disagree", "Strong…
$ norm_com6_likert7    &lt;chr&gt; "Strongly Agree", "Strongly Disagree", "Moderatel…
$ job_aff1_likert5     &lt;chr&gt; "Strongly Agree", "Strongly Agree", "Neutral", "S…
$ job_aff2_likert5     &lt;chr&gt; "Strongly Disagree", "Strongly Agree", "Strongly …
$ job_aff3_likert5     &lt;chr&gt; "Neutral", "Strongly Disagree", "Disagree", "Stro…
$ job_aff4_likert5     &lt;chr&gt; "Disagree", "Strongly Agree", "Agree", "Strongly …</code></pre>
</div>
</div>
<section id="sex" class="level5" data-number="2.5.3.2.1">
<h5 data-number="2.5.3.2.1" class="anchored" data-anchor-id="sex"><span class="header-section-number">2.5.3.2.1</span> Sex</h5>
<p>There is only one variable that we will convert to a factor and that’s the sex variable. We convert it to a factor with the command below.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert variables to factors as needed</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Convert sex to factor</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex =</span> <span class="fu">as_factor</span>(sex))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="participant-identification" class="level5" data-number="2.5.3.2.2">
<h5 data-number="2.5.3.2.2" class="anchored" data-anchor-id="participant-identification"><span class="header-section-number">2.5.3.2.2</span> Participant identification</h5>
<p>In many analyses we will need a column with a unique identification number that is a factor. We don’t see one in this data set so we create it with the name participant_id.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Participant identification to factor</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Participant identification column must be created first</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="do">## get the number of rows in the data set</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fu">dim</span>(analytic_data_survey)[<span class="dv">1</span>] </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="do">## create set of factor levels</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>participant_id_levels <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">seq</span>(<span class="dv">1</span>, N))</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="do">## put the factor levels into a column called participant_id</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">participant_id =</span> participant_id_levels)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>You can ensure all of these columns are now factors using the glimpse() command.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(sex, participant_id) <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 150
Columns: 2
$ sex            &lt;fct&gt; female, female, female, male, intersex, intersex, inter…
$ participant_id &lt;fct&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, …</code></pre>
</div>
</div>
</section>
</section>
<section id="factor-screening" class="level4" data-number="2.5.3.3">
<h4 data-number="2.5.3.3" class="anchored" data-anchor-id="factor-screening"><span class="header-section-number">2.5.3.3</span> Factor screening</h4>
<p>Inspect the levels of each factor carefully. Make sure the factor levels of each variable are correct. Examine spelling and look for additional unwanted levels. For example, you wouldn’t want to have the following levels for sex: male, mmale, female. Obviously, mmale is an incorrectly typed version of male. Scan all the factors in your data for erroneous factor levels. The code below displays the factor levels for sex:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Screen factors</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="do">## screen</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(sex) <span class="sc">%&gt;%</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       sex    
 female  :43  
 male    :49  
 intersex:58  </code></pre>
</div>
</div>
<p>You can see in the above output there are three levels for sex in this data set: female, male and intersex. You can also see beside each of these labels the number of participants for each category.</p>
<p>Notice the order of the factor levels: female, male, and intersex. This will be the order they appear in graphs and tables. We might want another order. If we did want another order, we could use the code below to establish the custom order for graphs and tables: female, intersex, male. Of course, you can use any order you want that makes sense for the context and your research question.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="do">## change to desired order</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex =</span> <span class="fu">fct_relevel</span>(sex,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"female"</span>,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"intersex"</span>,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"male"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="numeric-screening" class="level4" data-number="2.5.3.4">
<h4 data-number="2.5.3.4" class="anchored" data-anchor-id="numeric-screening"><span class="header-section-number">2.5.3.4</span> Numeric screening</h4>
<p>For numeric variables, it’s important to find and remove impossible values. We only have year_of_birth as a numeric column - so we can easily check for nonsense values with the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Screen numeric variables</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(year_of_birth) <span class="sc">%&gt;%</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  skim_variable n_missing    mean    sd   p0  p50 p100
1 year_of_birth         0 1973.88 20.06 1940 1970 2010</code></pre>
</div>
</div>
</section>
<section id="item-values-from-labels" class="level4" data-number="2.5.3.5">
<h4 data-number="2.5.3.5" class="anchored" data-anchor-id="item-values-from-labels"><span class="header-section-number">2.5.3.5</span> Item values from labels</h4>
<p>Recall that when we obtained our data from Qualtrics we selected “Use Choice Text”. That means that, as desired, we didn’t get values for our Likert items - we obtained labels. Now we need to switch the Likert responses to numeric values. The advantage of handling our data in this way is that anyone examining our data and code in an open access repository can see exactly what options survey participants were provided with for each question.</p>
<p>But prior to beginning check out the type for each Likert column below using the glimpse() command notice that are all of type “chr”.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 150
Columns: 26
$ duration_in_seconds  &lt;dbl&gt; 244, 134, 237, 110, 151, 92, 393, 165, 315, 262, …
$ year_of_birth        &lt;dbl&gt; 1961, 2006, 2008, 1985, 1953, 1957, 1998, 1970, 1…
$ sex                  &lt;fct&gt; female, female, female, male, intersex, intersex,…
$ aff_com1_likert7     &lt;chr&gt; "Slightly Agree", "Neither Agree nor Disagree", "…
$ aff_com2_likert7     &lt;chr&gt; "Slightly Agree", "Slightly Disagree", "Neither A…
$ aff_com3_likert7rev  &lt;chr&gt; "Strongly Disagree", "Neither Agree nor Disagree"…
$ aff_com4_likert7rev  &lt;chr&gt; "Moderately Disagree", "Strongly Agree", "Moderat…
$ aff_com5_likert7rev  &lt;chr&gt; "Strongly Disagree", "Neither Agree nor Disagree"…
$ aff_com6_likert7     &lt;chr&gt; "Moderately Agree", "Strongly Agree", "Strongly D…
$ contin_com1_likert7  &lt;chr&gt; "Strongly Agree", "Neither Agree nor Disagree", "…
$ contin_com2_likert7  &lt;chr&gt; "Slightly Agree", "Slightly Agree", "Slightly Dis…
$ contin_com3_likert7  &lt;chr&gt; "Strongly Disagree", "Slightly Disagree", "Strong…
$ contin_com4_likert7  &lt;chr&gt; "Moderately Agree", "Neither Agree nor Disagree",…
$ contin_com5_likert7  &lt;chr&gt; "Slightly Agree", "Slightly Agree", "Strongly Dis…
$ contin_com6_likert7  &lt;chr&gt; "Moderately Disagree", "Moderately Disagree", "St…
$ norm_com1_likert7rev &lt;chr&gt; "Neither Agree nor Disagree", "Slightly Disagree"…
$ norm_com2_likert7    &lt;chr&gt; "Moderately Disagree", "Moderately Agree", "Stron…
$ norm_com3_likert7    &lt;chr&gt; "Neither Agree nor Disagree", "Neither Agree nor …
$ norm_com4_likert7    &lt;chr&gt; "Moderately Disagree", "Moderately Disagree", "St…
$ norm_com5_likert7    &lt;chr&gt; "Strongly Disagree", "Strongly Disagree", "Strong…
$ norm_com6_likert7    &lt;chr&gt; "Strongly Agree", "Strongly Disagree", "Moderatel…
$ job_aff1_likert5     &lt;chr&gt; "Strongly Agree", "Strongly Agree", "Neutral", "S…
$ job_aff2_likert5     &lt;chr&gt; "Strongly Disagree", "Strongly Agree", "Strongly …
$ job_aff3_likert5     &lt;chr&gt; "Neutral", "Strongly Disagree", "Disagree", "Stro…
$ job_aff4_likert5     &lt;chr&gt; "Disagree", "Strongly Agree", "Agree", "Strongly …
$ participant_id       &lt;fct&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15…</code></pre>
</div>
</div>
<p>When you have type chr for a column the computer sees the content of each column as text that is different for each participant. It doesn’t even realize that two people who both responded “Slightly Agree” responded the same way. It sees every response in the column as unique. Check that out for the aff_com1_likert7 item.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(aff_com1_likert7) <span class="sc">%&gt;%</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summary</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> aff_com1_likert7  
 Length:150        
 Class :character  
 Mode  :character  </code></pre>
</div>
</div>
<section id="commitment-items" class="level5" data-number="2.5.3.5.1">
<h5 data-number="2.5.3.5.1" class="anchored" data-anchor-id="commitment-items"><span class="header-section-number">2.5.3.5.1</span> Commitment Items</h5>
<p>To convert a column from a character column to factor column we need know the exact labels used in that column. We can obtain those with the code below. In this code, we use just one item aff_com1_likert7. We determine the response options for that one item and will apply them to all the commitment items. We use the pull() command to obtain all the participant responses from the aff_com1_likert7. column. Then we use the unique() command to give use just one instance of each response.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert Commitment items to numeric  values</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Check levels for a likert7 item</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(aff_com1_likert7) <span class="sc">%&gt;%</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Slightly Agree"             "Neither Agree nor Disagree"
[3] "Moderately Disagree"        "Strongly Agree"            
[5] "Strongly Disagree"          "Moderately Agree"          
[7] "Slightly Disagree"         </code></pre>
</div>
</div>
<p>Now that we know the labels used in that column (and all the commitment columns that end in likert7) we create an ordered version of those labels with the code below. I copied and pasted the text (e.g., “Strongly Disagree”) from the above output to avoid typos.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="do">## write code to create ordered factor labels/levels</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>likert7_factor <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Strongly Disagree"</span>,</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Moderately Disagree"</span>,</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Slightly Disagree"</span>,</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Neither Agree nor Disagree"</span>,</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Slightly Agree"</span>,</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Moderately Agree"</span>,</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Strongly Agree"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now we turn each column of text (i.e., type chr) into a factor column using the factor levels/labels we created:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="do">## assign factor levels</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">contains</span>(<span class="st">"likert7"</span>), </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">.fns =</span> <span class="sc">~</span> <span class="fu">factor</span>(.x, <span class="at">levels =</span> likert7_factor)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>In this code we use the mutate() command to modify columns. We use the across() command to have the single mutate command apply to several columns. Within the across() command we use contains(“likert7”) to apply the mutate() command only to columns with likert7 in the name. <strong>You can see why column naming conventions are so important!</strong> Next, within the across() command, we specify .fns. This indicate the function/command that will apply to the columns selected. The ~ before “factor” just warns the computer that what comes next is a function/command name. The factor() command is what will be applied to the columns. The .x within the factor command is a placeholder for each column name that will be obtained by the previous contains() command.</p>
<p>After this mutate() command is used you can see the columns with likert7 in the name are now factors.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(analytic_data_survey)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 150
Columns: 26
$ duration_in_seconds  &lt;dbl&gt; 244, 134, 237, 110, 151, 92, 393, 165, 315, 262, …
$ year_of_birth        &lt;dbl&gt; 1961, 2006, 2008, 1985, 1953, 1957, 1998, 1970, 1…
$ sex                  &lt;fct&gt; female, female, female, male, intersex, intersex,…
$ aff_com1_likert7     &lt;fct&gt; Slightly Agree, Neither Agree nor Disagree, Moder…
$ aff_com2_likert7     &lt;fct&gt; Slightly Agree, Slightly Disagree, Neither Agree …
$ aff_com3_likert7rev  &lt;fct&gt; Strongly Disagree, Neither Agree nor Disagree, Mo…
$ aff_com4_likert7rev  &lt;fct&gt; Moderately Disagree, Strongly Agree, Moderately A…
$ aff_com5_likert7rev  &lt;fct&gt; Strongly Disagree, Neither Agree nor Disagree, Mo…
$ aff_com6_likert7     &lt;fct&gt; Moderately Agree, Strongly Agree, Strongly Disagr…
$ contin_com1_likert7  &lt;fct&gt; Strongly Agree, Neither Agree nor Disagree, Stron…
$ contin_com2_likert7  &lt;fct&gt; Slightly Agree, Slightly Agree, Slightly Disagree…
$ contin_com3_likert7  &lt;fct&gt; Strongly Disagree, Slightly Disagree, Strongly Ag…
$ contin_com4_likert7  &lt;fct&gt; Moderately Agree, Neither Agree nor Disagree, Sli…
$ contin_com5_likert7  &lt;fct&gt; Slightly Agree, Slightly Agree, Strongly Disagree…
$ contin_com6_likert7  &lt;fct&gt; Moderately Disagree, Moderately Disagree, Strongl…
$ norm_com1_likert7rev &lt;fct&gt; Neither Agree nor Disagree, Slightly Disagree, Mo…
$ norm_com2_likert7    &lt;fct&gt; Moderately Disagree, Moderately Agree, Strongly D…
$ norm_com3_likert7    &lt;fct&gt; Neither Agree nor Disagree, Neither Agree nor Dis…
$ norm_com4_likert7    &lt;fct&gt; Moderately Disagree, Moderately Disagree, Strongl…
$ norm_com5_likert7    &lt;fct&gt; Strongly Disagree, Strongly Disagree, Strongly Di…
$ norm_com6_likert7    &lt;fct&gt; Strongly Agree, Strongly Disagree, Moderately Dis…
$ job_aff1_likert5     &lt;chr&gt; "Strongly Agree", "Strongly Agree", "Neutral", "S…
$ job_aff2_likert5     &lt;chr&gt; "Strongly Disagree", "Strongly Agree", "Strongly …
$ job_aff3_likert5     &lt;chr&gt; "Neutral", "Strongly Disagree", "Disagree", "Stro…
$ job_aff4_likert5     &lt;chr&gt; "Disagree", "Strongly Agree", "Agree", "Strongly …
$ participant_id       &lt;fct&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15…</code></pre>
</div>
</div>
<p>Now examine aff_com1_likert7 again - you can see it has levels:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(aff_com1_likert7) <span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summary</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   aff_com1_likert7
 Strongly Disagree         :21     
 Moderately Disagree       :21     
 Slightly Disagree         :21     
 Neither Agree nor Disagree:18     
 Slightly Agree            :28     
 Moderately Agree          :21     
 Strongly Agree            :20     </code></pre>
</div>
</div>
<p>The second step in our conversion process is converting each column from a factor to the numeric value associated with the factor level (i.e.&nbsp;Strongly Disagree becomes 1). We do so with the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="do">## covert factor levels to numeric values</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">contains</span>(<span class="st">"likert7"</span>), </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">.fns =</span> as.numeric))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>You can see there are numeric values with the code below. Notice the column types for likert7 items is now dbl (short for double - a type of high precision number.)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(analytic_data_survey)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 150
Columns: 26
$ duration_in_seconds  &lt;dbl&gt; 244, 134, 237, 110, 151, 92, 393, 165, 315, 262, …
$ year_of_birth        &lt;dbl&gt; 1961, 2006, 2008, 1985, 1953, 1957, 1998, 1970, 1…
$ sex                  &lt;fct&gt; female, female, female, male, intersex, intersex,…
$ aff_com1_likert7     &lt;dbl&gt; 5, 4, 2, 7, 1, 6, 6, 2, 4, 2, 5, 4, 7, 3, 1, 7, 3…
$ aff_com2_likert7     &lt;dbl&gt; 5, 3, 4, 2, 6, 7, 2, 3, 2, 7, 3, 4, 4, 1, 6, 2, 5…
$ aff_com3_likert7rev  &lt;dbl&gt; 1, 4, 2, 5, 7, 2, 6, 3, 5, 4, 3, 3, 2, 2, 6, 2, 7…
$ aff_com4_likert7rev  &lt;dbl&gt; 2, 7, 6, 6, 3, 5, 7, 6, 7, 2, 7, 2, 5, 6, 1, 4, 4…
$ aff_com5_likert7rev  &lt;dbl&gt; 1, 4, 6, 5, 3, 7, 5, 7, 5, 5, 4, 5, 3, 1, 3, 2, 4…
$ aff_com6_likert7     &lt;dbl&gt; 6, 7, 1, 7, 5, 6, 5, 7, 4, 2, 7, 7, 5, 3, 2, 4, 4…
$ contin_com1_likert7  &lt;dbl&gt; 7, 4, 1, 3, 2, 1, 1, 6, 7, 3, 6, 2, 2, 5, 5, 3, 5…
$ contin_com2_likert7  &lt;dbl&gt; 5, 5, 3, 2, 7, 6, 1, 3, 5, 2, 4, 5, 1, 6, 6, 6, 2…
$ contin_com3_likert7  &lt;dbl&gt; 1, 3, 7, 7, 5, 2, 7, 2, 7, 1, 4, 2, 4, 5, 6, 1, 6…
$ contin_com4_likert7  &lt;dbl&gt; 6, 4, 3, 7, 7, 5, 4, 5, 3, 2, 2, 4, 2, 7, 3, 7, 5…
$ contin_com5_likert7  &lt;dbl&gt; 5, 5, 1, 4, 4, 6, 5, 5, 5, 2, 5, 6, 3, 5, 2, 7, 6…
$ contin_com6_likert7  &lt;dbl&gt; 2, 2, 1, 4, 7, 7, 6, 6, 4, 5, 2, 5, 5, 5, 5, 5, 3…
$ norm_com1_likert7rev &lt;dbl&gt; 4, 3, 6, 3, 3, 6, 5, 7, 3, 7, 5, 1, 5, 3, 5, 4, 2…
$ norm_com2_likert7    &lt;dbl&gt; 2, 6, 1, 5, 3, 2, 3, 1, 7, 1, 1, 6, 6, 6, 7, 6, 4…
$ norm_com3_likert7    &lt;dbl&gt; 4, 4, 7, 3, 1, 1, 4, 3, 3, 5, 3, 5, 2, 3, 2, 3, 1…
$ norm_com4_likert7    &lt;dbl&gt; 2, 2, 1, 6, 4, 6, 1, 1, 5, 5, 5, 3, 2, 3, 3, 5, 5…
$ norm_com5_likert7    &lt;dbl&gt; 1, 1, 1, 5, 7, 4, 3, 6, 4, 4, 1, 3, 3, 1, 6, 1, 7…
$ norm_com6_likert7    &lt;dbl&gt; 7, 1, 2, 4, 6, 6, 1, 4, 6, 2, 1, 4, 1, 5, 6, 3, 4…
$ job_aff1_likert5     &lt;chr&gt; "Strongly Agree", "Strongly Agree", "Neutral", "S…
$ job_aff2_likert5     &lt;chr&gt; "Strongly Disagree", "Strongly Agree", "Strongly …
$ job_aff3_likert5     &lt;chr&gt; "Neutral", "Strongly Disagree", "Disagree", "Stro…
$ job_aff4_likert5     &lt;chr&gt; "Disagree", "Strongly Agree", "Agree", "Strongly …
$ participant_id       &lt;fct&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15…</code></pre>
</div>
</div>
<p>If you run the summary() command on the aff_com1_likert7 you see we have values now.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span> </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(aff_com1_likert7) <span class="sc">%&gt;%</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summary</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> aff_com1_likert7
 Min.   :1.000   
 1st Qu.:2.000   
 Median :4.000   
 Mean   :4.027   
 3rd Qu.:6.000   
 Max.   :7.000   </code></pre>
</div>
</div>
<p>Side note: We did a lot of explaining as we went through the steps above. But it’s not as long as it seems. Some of the steps can even be combined. See the concise version of the code we used repeated below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert Commitment items to numeric  values</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Check levels for a likert7 item</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(aff_com1_likert7) <span class="sc">%&gt;%</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>()</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="do">## write code to create ordered factor labels/levels</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>likert7_factor <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Strongly Disagree"</span>,</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Moderately Disagree"</span>,</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Slightly Disagree"</span>,</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Neither Agree nor Disagree"</span>,</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Slightly Agree"</span>,</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Moderately Agree"</span>,</span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Strongly Agree"</span>)</span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a><span class="do">## assign factor levels and then covert to numeric</span></span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">contains</span>(<span class="st">"likert7"</span>), </span>
<span id="cb42-20"><a href="#cb42-20" aria-hidden="true" tabindex="-1"></a>                <span class="at">.fns =</span> <span class="sc">~</span> <span class="fu">factor</span>(.x, <span class="at">levels =</span> likert7_factor))) <span class="sc">%&gt;%</span></span>
<span id="cb42-21"><a href="#cb42-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">contains</span>(<span class="st">"likert7"</span>), </span>
<span id="cb42-22"><a href="#cb42-22" aria-hidden="true" tabindex="-1"></a>                <span class="at">.fns =</span> as.numeric))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="job-satisfaction-conversion" class="level5" data-number="2.5.3.5.2">
<h5 data-number="2.5.3.5.2" class="anchored" data-anchor-id="job-satisfaction-conversion"><span class="header-section-number">2.5.3.5.2</span> Job Satisfaction Conversion</h5>
<p>We’ll skip all the explanation steps for Job Satisfaction and just show you the essentials. First, get the labels for the items:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert Job Satisfaction items to numeric  values</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Check levels for a likert5 item</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(job_aff1_likert5) <span class="sc">%&gt;%</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Strongly Agree"    "Neutral"           "Strongly Disagree"
[4] "Agree"             "Disagree"         </code></pre>
</div>
</div>
<p>Second, create the ordered factor labels:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="do">## write code to create ordered factor labels/levels</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>likert5_factor <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Strongly Disagree"</span>,</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Disagree"</span>,</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Neutral"</span>,</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Agree"</span>,</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Strongly Agree"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Third, convert the columns to a factor and then to numbers.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="do">## assign factor levels and then covert to numeric</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">contains</span>(<span class="st">"likert5"</span>), </span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">.fns =</span> <span class="sc">~</span> <span class="fu">factor</span>(.x, <span class="at">levels =</span> likert5_factor))) <span class="sc">%&gt;%</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">contains</span>(<span class="st">"likert5"</span>), </span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">.fns =</span> as.numeric))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="scale-scores" class="level4" data-number="2.5.3.6">
<h4 data-number="2.5.3.6" class="anchored" data-anchor-id="scale-scores"><span class="header-section-number">2.5.3.6</span> Scale scores</h4>
<p>For each person, scale scores involve averaging scores from several items to create an overall score. The first step in the creation of scales is correcting the values of any reverse-keyed items.</p>
<section id="reverse-key-items" class="level5" data-number="2.5.3.6.1">
<h5 data-number="2.5.3.6.1" class="anchored" data-anchor-id="reverse-key-items"><span class="header-section-number">2.5.3.6.1</span> Reverse-key items</h5>
<p>A complete discussion of the logic for flipping reverse-key (i.e., reverse worded) items is provide the previous chapter in the <a href="https://dstanley4.github.io/psyc6060bookdown/an-emphasis-on-workflow.html#scale-scores">Scale Scores</a> section. We use that logic in the script below.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reverse key items</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Reverse key likert7 items</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span> </span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="dv">8</span> <span class="sc">-</span> <span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">ends_with</span>(<span class="st">"_likert7rev"</span>)) ) <span class="sc">%&gt;%</span> </span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename_with</span>(<span class="at">.fn =</span> str_replace,</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">.cols =</span> <span class="fu">ends_with</span>(<span class="st">"_likert7rev"</span>),</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">pattern =</span> <span class="st">"_likert7rev"</span>,</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">replacement =</span> <span class="st">"_likert7"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>You can see that are all keyed in the right direction now.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(analytic_data_survey)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 150
Columns: 26
$ duration_in_seconds &lt;dbl&gt; 244, 134, 237, 110, 151, 92, 393, 165, 315, 262, 3…
$ year_of_birth       &lt;dbl&gt; 1961, 2006, 2008, 1985, 1953, 1957, 1998, 1970, 19…
$ sex                 &lt;fct&gt; female, female, female, male, intersex, intersex, …
$ aff_com1_likert7    &lt;dbl&gt; 5, 4, 2, 7, 1, 6, 6, 2, 4, 2, 5, 4, 7, 3, 1, 7, 3,…
$ aff_com2_likert7    &lt;dbl&gt; 5, 3, 4, 2, 6, 7, 2, 3, 2, 7, 3, 4, 4, 1, 6, 2, 5,…
$ aff_com3_likert7    &lt;dbl&gt; 7, 4, 6, 3, 1, 6, 2, 5, 3, 4, 5, 5, 6, 6, 2, 6, 1,…
$ aff_com4_likert7    &lt;dbl&gt; 6, 1, 2, 2, 5, 3, 1, 2, 1, 6, 1, 6, 3, 2, 7, 4, 4,…
$ aff_com5_likert7    &lt;dbl&gt; 7, 4, 2, 3, 5, 1, 3, 1, 3, 3, 4, 3, 5, 7, 5, 6, 4,…
$ aff_com6_likert7    &lt;dbl&gt; 6, 7, 1, 7, 5, 6, 5, 7, 4, 2, 7, 7, 5, 3, 2, 4, 4,…
$ contin_com1_likert7 &lt;dbl&gt; 7, 4, 1, 3, 2, 1, 1, 6, 7, 3, 6, 2, 2, 5, 5, 3, 5,…
$ contin_com2_likert7 &lt;dbl&gt; 5, 5, 3, 2, 7, 6, 1, 3, 5, 2, 4, 5, 1, 6, 6, 6, 2,…
$ contin_com3_likert7 &lt;dbl&gt; 1, 3, 7, 7, 5, 2, 7, 2, 7, 1, 4, 2, 4, 5, 6, 1, 6,…
$ contin_com4_likert7 &lt;dbl&gt; 6, 4, 3, 7, 7, 5, 4, 5, 3, 2, 2, 4, 2, 7, 3, 7, 5,…
$ contin_com5_likert7 &lt;dbl&gt; 5, 5, 1, 4, 4, 6, 5, 5, 5, 2, 5, 6, 3, 5, 2, 7, 6,…
$ contin_com6_likert7 &lt;dbl&gt; 2, 2, 1, 4, 7, 7, 6, 6, 4, 5, 2, 5, 5, 5, 5, 5, 3,…
$ norm_com1_likert7   &lt;dbl&gt; 4, 5, 2, 5, 5, 2, 3, 1, 5, 1, 3, 7, 3, 5, 3, 4, 6,…
$ norm_com2_likert7   &lt;dbl&gt; 2, 6, 1, 5, 3, 2, 3, 1, 7, 1, 1, 6, 6, 6, 7, 6, 4,…
$ norm_com3_likert7   &lt;dbl&gt; 4, 4, 7, 3, 1, 1, 4, 3, 3, 5, 3, 5, 2, 3, 2, 3, 1,…
$ norm_com4_likert7   &lt;dbl&gt; 2, 2, 1, 6, 4, 6, 1, 1, 5, 5, 5, 3, 2, 3, 3, 5, 5,…
$ norm_com5_likert7   &lt;dbl&gt; 1, 1, 1, 5, 7, 4, 3, 6, 4, 4, 1, 3, 3, 1, 6, 1, 7,…
$ norm_com6_likert7   &lt;dbl&gt; 7, 1, 2, 4, 6, 6, 1, 4, 6, 2, 1, 4, 1, 5, 6, 3, 4,…
$ job_aff1_likert5    &lt;dbl&gt; 5, 5, 3, 1, 1, 3, 4, 4, 1, 4, 3, 5, 5, 1, 2, 1, 3,…
$ job_aff2_likert5    &lt;dbl&gt; 1, 5, 5, 2, 3, 1, 3, 3, 5, 5, 4, 3, 1, 1, 5, 3, 5,…
$ job_aff3_likert5    &lt;dbl&gt; 3, 1, 2, 5, 5, 3, 3, 1, 5, 2, 3, 4, 5, 4, 2, 3, 3,…
$ job_aff4_likert5    &lt;dbl&gt; 2, 5, 4, 1, 5, 3, 1, 3, 3, 5, 2, 5, 2, 3, 1, 5, 5,…
$ participant_id      &lt;fct&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,…</code></pre>
</div>
</div>
<p>None of the job satisfaction items were reverse-keyed.</p>
</section>
<section id="creating-scores" class="level5" data-number="2.5.3.6.2">
<h5 data-number="2.5.3.6.2" class="anchored" data-anchor-id="creating-scores"><span class="header-section-number">2.5.3.6.2</span> Creating scores</h5>
<p><strong>Important:</strong> Take note of how we name the scale variables (e.g., affective_commitment) with a different prefix than the items (e..g, aff_com1_likert7). This allows us to delete the items (i.e., columns that start with aff_com) but not the final scale score (i.e., a column starts with affective_commitment). This example again illustrates how carefully you need to think about your column and scale naming conventions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create scale scores</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="do">## mutate commands create scale scores</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="do">## select commands with "-" remove items after scale creation</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span> </span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">affective_commitment =</span> <span class="fu">mean</span>(<span class="fu">c_across</span>(<span class="fu">starts_with</span>(<span class="st">"aff_com"</span>)),</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">continuance_commitment =</span> <span class="fu">mean</span>(<span class="fu">c_across</span>(<span class="fu">starts_with</span>(<span class="st">"contin_com"</span>)),</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>                                       <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">normative_commitment =</span> <span class="fu">mean</span>(<span class="fu">c_across</span>(<span class="fu">starts_with</span>(<span class="st">"norm_com"</span>)),</span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">job_satisfaction =</span> <span class="fu">mean</span>(<span class="fu">c_across</span>(<span class="fu">starts_with</span>(<span class="st">"job_aff"</span>)),</span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">starts_with</span>(<span class="st">"aff_com"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb50-16"><a href="#cb50-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">starts_with</span>(<span class="st">"contin_com"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb50-17"><a href="#cb50-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">starts_with</span>(<span class="st">"norm_com"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb50-18"><a href="#cb50-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">starts_with</span>(<span class="st">"job_aff"</span>)) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We can see our data now has the columns: affective_commitment, continuance_commitment, normative_commitment, job satisfaction.</p>
<p>As well, all of the items used to create the scale scores have been removed.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(analytic_data_survey)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 150
Columns: 8
$ duration_in_seconds    &lt;dbl&gt; 244, 134, 237, 110, 151, 92, 393, 165, 315, 262…
$ year_of_birth          &lt;dbl&gt; 1961, 2006, 2008, 1985, 1953, 1957, 1998, 1970,…
$ sex                    &lt;fct&gt; female, female, female, male, intersex, interse…
$ participant_id         &lt;fct&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, …
$ affective_commitment   &lt;dbl&gt; 6.000000, 3.833333, 2.833333, 4.000000, 3.83333…
$ continuance_commitment &lt;dbl&gt; 4.333333, 3.833333, 2.666667, 4.500000, 5.33333…
$ normative_commitment   &lt;dbl&gt; 3.333333, 3.166667, 2.333333, 4.666667, 4.33333…
$ job_satisfaction       &lt;dbl&gt; 2.75, 4.00, 3.50, 2.25, 3.50, 2.50, 2.75, 2.75,…</code></pre>
</div>
</div>
</section>
<section id="removing-fast-responders" class="level5" data-number="2.5.3.6.3">
<h5 data-number="2.5.3.6.3" class="anchored" data-anchor-id="removing-fast-responders"><span class="header-section-number">2.5.3.6.3</span> Removing fast responders</h5>
<p>You might be interested in removing people who responded to the survey too quickly. Notice two things when we glimpse the ananlytic_data_survey data below.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(analytic_data_survey)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 150
Columns: 8
$ duration_in_seconds    &lt;dbl&gt; 244, 134, 237, 110, 151, 92, 393, 165, 315, 262…
$ year_of_birth          &lt;dbl&gt; 1961, 2006, 2008, 1985, 1953, 1957, 1998, 1970,…
$ sex                    &lt;fct&gt; female, female, female, male, intersex, interse…
$ participant_id         &lt;fct&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, …
$ affective_commitment   &lt;dbl&gt; 6.000000, 3.833333, 2.833333, 4.000000, 3.83333…
$ continuance_commitment &lt;dbl&gt; 4.333333, 3.833333, 2.666667, 4.500000, 5.33333…
$ normative_commitment   &lt;dbl&gt; 3.333333, 3.166667, 2.333333, 4.666667, 4.33333…
$ job_satisfaction       &lt;dbl&gt; 2.75, 4.00, 3.50, 2.25, 3.50, 2.50, 2.75, 2.75,…</code></pre>
</div>
</div>
<p>First, there are 150 rows so there are 150 participants in this data set. Second, there is a column called duration_in_seconds. You can use this column to remove people who responded too quickly. For example, you might decide that anyone who responded in less than 120 seconds (i.e., 2 minutes) should be removed from the data set. You can do so with the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(duration_in_seconds <span class="sc">&gt;=</span> <span class="dv">120</span>)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(analytic_data_survey)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 129
Columns: 8
$ duration_in_seconds    &lt;dbl&gt; 244, 134, 237, 151, 393, 165, 315, 262, 370, 20…
$ year_of_birth          &lt;dbl&gt; 1961, 2006, 2008, 1953, 1998, 1970, 1983, 1959,…
$ sex                    &lt;fct&gt; female, female, female, intersex, intersex, mal…
$ participant_id         &lt;fct&gt; 1, 2, 3, 5, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17…
$ affective_commitment   &lt;dbl&gt; 6.000000, 3.833333, 2.833333, 3.833333, 3.16666…
$ continuance_commitment &lt;dbl&gt; 4.333333, 3.833333, 2.666667, 5.333333, 4.00000…
$ normative_commitment   &lt;dbl&gt; 3.333333, 3.166667, 2.333333, 4.333333, 2.50000…
$ job_satisfaction       &lt;dbl&gt; 2.75, 4.00, 3.50, 3.50, 2.75, 2.75, 3.50, 4.00,…</code></pre>
</div>
</div>
<p>This reduces the data set to the 129 people who took at least 2 minutes (i.e., 120 seconds) to complete the survey.</p>
</section>
</section>
</section>
<section id="complete-script" class="level3" data-number="2.5.4">
<h3 data-number="2.5.4" class="anchored" data-anchor-id="complete-script"><span class="header-section-number">2.5.4</span> Complete script</h3>
<p>The complete script <a href="script_qualtrics.R">script_qualtrics.R</a> for the data file <a href="data_qualtrics.csv">data_qualtrics.csv</a> is presented below.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Date: YYYY-MM-DD</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Name: your name here</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Example: Single occasion survey</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a><span class="co"># read just the header row to get column names</span></span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>survey_file <span class="ot">&lt;-</span> <span class="st">"data_qualtrics.csv"</span></span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>col_names <span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">read_csv</span>(survey_file,</span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a>                            <span class="at">n_max =</span> <span class="dv">0</span>,</span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a>                            <span class="at">show_col_types =</span> <span class="cn">FALSE</span>))</span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a><span class="co"># skip the first 3 rows, read data using names from above</span></span>
<span id="cb57-16"><a href="#cb57-16" aria-hidden="true" tabindex="-1"></a>raw_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(survey_file,</span>
<span id="cb57-17"><a href="#cb57-17" aria-hidden="true" tabindex="-1"></a>                     <span class="at">col_names =</span> col_names, </span>
<span id="cb57-18"><a href="#cb57-18" aria-hidden="true" tabindex="-1"></a>                     <span class="at">skip =</span> <span class="dv">3</span>,</span>
<span id="cb57-19"><a href="#cb57-19" aria-hidden="true" tabindex="-1"></a>                     <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb57-20"><a href="#cb57-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-21"><a href="#cb57-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Qualtrics columns to remove (any_of() ignores names not present)</span></span>
<span id="cb57-22"><a href="#cb57-22" aria-hidden="true" tabindex="-1"></a>cols_to_remove <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"StartDate"</span>,</span>
<span id="cb57-23"><a href="#cb57-23" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"EndDate"</span>,</span>
<span id="cb57-24"><a href="#cb57-24" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Status"</span>,</span>
<span id="cb57-25"><a href="#cb57-25" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"IPAddress"</span>,</span>
<span id="cb57-26"><a href="#cb57-26" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Progress"</span>,</span>
<span id="cb57-27"><a href="#cb57-27" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Finished"</span>,</span>
<span id="cb57-28"><a href="#cb57-28" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"RecordedDate"</span>,</span>
<span id="cb57-29"><a href="#cb57-29" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"ResponseId"</span>,</span>
<span id="cb57-30"><a href="#cb57-30" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"RecipientLastName"</span>,</span>
<span id="cb57-31"><a href="#cb57-31" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"RecipientFirstName"</span>,</span>
<span id="cb57-32"><a href="#cb57-32" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"RecipientEmail"</span>,</span>
<span id="cb57-33"><a href="#cb57-33" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"ExternalReference"</span>,</span>
<span id="cb57-34"><a href="#cb57-34" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"LocationLatitude"</span>,</span>
<span id="cb57-35"><a href="#cb57-35" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"LocationLongitude"</span>,</span>
<span id="cb57-36"><a href="#cb57-36" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"DistributionChannel"</span>,</span>
<span id="cb57-37"><a href="#cb57-37" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"UserLanguage"</span>)</span>
<span id="cb57-38"><a href="#cb57-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-39"><a href="#cb57-39" aria-hidden="true" tabindex="-1"></a><span class="co"># remove the unwanted Qualtrics columns</span></span>
<span id="cb57-40"><a href="#cb57-40" aria-hidden="true" tabindex="-1"></a>raw_data <span class="ot">&lt;-</span> raw_data <span class="sc">|&gt;</span> </span>
<span id="cb57-41"><a href="#cb57-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">!</span><span class="fu">any_of</span>(cols_to_remove))</span>
<span id="cb57-42"><a href="#cb57-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-43"><a href="#cb57-43" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> raw_data</span>
<span id="cb57-44"><a href="#cb57-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-45"><a href="#cb57-45" aria-hidden="true" tabindex="-1"></a><span class="co"># Initial cleaning</span></span>
<span id="cb57-46"><a href="#cb57-46" aria-hidden="true" tabindex="-1"></a><span class="do">## Convert column names to tidyverse style guide</span></span>
<span id="cb57-47"><a href="#cb57-47" aria-hidden="true" tabindex="-1"></a><span class="do">## Remove empty rows and columns</span></span>
<span id="cb57-48"><a href="#cb57-48" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb57-49"><a href="#cb57-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">remove_empty</span>(<span class="st">"rows"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb57-50"><a href="#cb57-50" aria-hidden="true" tabindex="-1"></a>  <span class="fu">remove_empty</span>(<span class="st">"cols"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb57-51"><a href="#cb57-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>()</span>
<span id="cb57-52"><a href="#cb57-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-53"><a href="#cb57-53" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(analytic_data_survey)</span>
<span id="cb57-54"><a href="#cb57-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-55"><a href="#cb57-55" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert variables to factors as needed</span></span>
<span id="cb57-56"><a href="#cb57-56" aria-hidden="true" tabindex="-1"></a><span class="do">## Convert sex to factor</span></span>
<span id="cb57-57"><a href="#cb57-57" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb57-58"><a href="#cb57-58" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex =</span> <span class="fu">as_factor</span>(sex))</span>
<span id="cb57-59"><a href="#cb57-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-60"><a href="#cb57-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-61"><a href="#cb57-61" aria-hidden="true" tabindex="-1"></a><span class="do">## Participant identification to factor</span></span>
<span id="cb57-62"><a href="#cb57-62" aria-hidden="true" tabindex="-1"></a><span class="do">## Participant identification column must be created first</span></span>
<span id="cb57-63"><a href="#cb57-63" aria-hidden="true" tabindex="-1"></a><span class="do">## get the number of rows in the data set</span></span>
<span id="cb57-64"><a href="#cb57-64" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fu">dim</span>(analytic_data_survey)[<span class="dv">1</span>] </span>
<span id="cb57-65"><a href="#cb57-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-66"><a href="#cb57-66" aria-hidden="true" tabindex="-1"></a><span class="do">## create set of factor levels</span></span>
<span id="cb57-67"><a href="#cb57-67" aria-hidden="true" tabindex="-1"></a>participant_id_levels <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">seq</span>(<span class="dv">1</span>, N))</span>
<span id="cb57-68"><a href="#cb57-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-69"><a href="#cb57-69" aria-hidden="true" tabindex="-1"></a><span class="do">## put the factor levels into a column called participant_id</span></span>
<span id="cb57-70"><a href="#cb57-70" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb57-71"><a href="#cb57-71" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">participant_id =</span> participant_id_levels)</span>
<span id="cb57-72"><a href="#cb57-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-73"><a href="#cb57-73" aria-hidden="true" tabindex="-1"></a><span class="co"># Screen factors</span></span>
<span id="cb57-74"><a href="#cb57-74" aria-hidden="true" tabindex="-1"></a><span class="do">## screen</span></span>
<span id="cb57-75"><a href="#cb57-75" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb57-76"><a href="#cb57-76" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(sex) <span class="sc">%&gt;%</span></span>
<span id="cb57-77"><a href="#cb57-77" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span>
<span id="cb57-78"><a href="#cb57-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-79"><a href="#cb57-79" aria-hidden="true" tabindex="-1"></a><span class="co"># Check existing levels (a different way than lines above)</span></span>
<span id="cb57-80"><a href="#cb57-80" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(analytic_data_survey<span class="sc">$</span>sex)</span>
<span id="cb57-81"><a href="#cb57-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-82"><a href="#cb57-82" aria-hidden="true" tabindex="-1"></a><span class="do">## change to desired order</span></span>
<span id="cb57-83"><a href="#cb57-83" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb57-84"><a href="#cb57-84" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex =</span> <span class="fu">fct_relevel</span>(sex,</span>
<span id="cb57-85"><a href="#cb57-85" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"female"</span>,</span>
<span id="cb57-86"><a href="#cb57-86" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"intersex"</span>,</span>
<span id="cb57-87"><a href="#cb57-87" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"male"</span>))</span>
<span id="cb57-88"><a href="#cb57-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-89"><a href="#cb57-89" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for unexpected levels</span></span>
<span id="cb57-90"><a href="#cb57-90" aria-hidden="true" tabindex="-1"></a>expected_sex <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"female"</span>, <span class="st">"intersex"</span>, <span class="st">"male"</span>)</span>
<span id="cb57-91"><a href="#cb57-91" aria-hidden="true" tabindex="-1"></a>unexpected <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(<span class="fu">levels</span>(analytic_data_survey<span class="sc">$</span>sex), expected_sex)</span>
<span id="cb57-92"><a href="#cb57-92" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">length</span>(unexpected) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb57-93"><a href="#cb57-93" aria-hidden="true" tabindex="-1"></a>  <span class="fu">warning</span>(<span class="st">"Unexpected sex levels found: "</span>, <span class="fu">paste</span>(unexpected, <span class="at">collapse =</span> <span class="st">", "</span>))</span>
<span id="cb57-94"><a href="#cb57-94" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb57-95"><a href="#cb57-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-96"><a href="#cb57-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-97"><a href="#cb57-97" aria-hidden="true" tabindex="-1"></a><span class="co"># Screen numeric variables</span></span>
<span id="cb57-98"><a href="#cb57-98" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb57-99"><a href="#cb57-99" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(year_of_birth) <span class="sc">%&gt;%</span></span>
<span id="cb57-100"><a href="#cb57-100" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim</span>()</span>
<span id="cb57-101"><a href="#cb57-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-102"><a href="#cb57-102" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb57-103"><a href="#cb57-103" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert Commitment items to numeric  values</span></span>
<span id="cb57-104"><a href="#cb57-104" aria-hidden="true" tabindex="-1"></a><span class="do">## Check levels for a likert7 item</span></span>
<span id="cb57-105"><a href="#cb57-105" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb57-106"><a href="#cb57-106" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(aff_com1_likert7) <span class="sc">%&gt;%</span></span>
<span id="cb57-107"><a href="#cb57-107" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>()</span>
<span id="cb57-108"><a href="#cb57-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-109"><a href="#cb57-109" aria-hidden="true" tabindex="-1"></a><span class="do">## Define word-to-number mapping 7-</span></span>
<span id="cb57-110"><a href="#cb57-110" aria-hidden="true" tabindex="-1"></a>likert7_recode <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb57-111"><a href="#cb57-111" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Strongly Disagree"</span> <span class="ot">=</span> <span class="dv">1</span>,</span>
<span id="cb57-112"><a href="#cb57-112" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Moderately Disagree"</span> <span class="ot">=</span> <span class="dv">2</span>,</span>
<span id="cb57-113"><a href="#cb57-113" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Slightly Disagree"</span> <span class="ot">=</span> <span class="dv">3</span>,</span>
<span id="cb57-114"><a href="#cb57-114" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Neither Agree nor Disagree"</span> <span class="ot">=</span> <span class="dv">4</span>,</span>
<span id="cb57-115"><a href="#cb57-115" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Slightly Agree"</span> <span class="ot">=</span> <span class="dv">5</span>,</span>
<span id="cb57-116"><a href="#cb57-116" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Moderately Agree"</span> <span class="ot">=</span> <span class="dv">6</span>,</span>
<span id="cb57-117"><a href="#cb57-117" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Strongly Agree"</span> <span class="ot">=</span> <span class="dv">7</span></span>
<span id="cb57-118"><a href="#cb57-118" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb57-119"><a href="#cb57-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-120"><a href="#cb57-120" aria-hidden="true" tabindex="-1"></a><span class="do">## Convert text responses to numeric values</span></span>
<span id="cb57-121"><a href="#cb57-121" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb57-122"><a href="#cb57-122" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(</span>
<span id="cb57-123"><a href="#cb57-123" aria-hidden="true" tabindex="-1"></a>    <span class="at">.cols =</span> <span class="fu">contains</span>(<span class="st">"likert7"</span>), </span>
<span id="cb57-124"><a href="#cb57-124" aria-hidden="true" tabindex="-1"></a>    <span class="at">.fns =</span> <span class="sc">~</span> likert7_recode[.x]</span>
<span id="cb57-125"><a href="#cb57-125" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb57-126"><a href="#cb57-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-127"><a href="#cb57-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-128"><a href="#cb57-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-129"><a href="#cb57-129" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert Job Satisfaction items to numeric  values</span></span>
<span id="cb57-130"><a href="#cb57-130" aria-hidden="true" tabindex="-1"></a><span class="do">## Check levels for a likert5 item</span></span>
<span id="cb57-131"><a href="#cb57-131" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb57-132"><a href="#cb57-132" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(job_aff1_likert5) <span class="sc">%&gt;%</span></span>
<span id="cb57-133"><a href="#cb57-133" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>()</span>
<span id="cb57-134"><a href="#cb57-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-135"><a href="#cb57-135" aria-hidden="true" tabindex="-1"></a><span class="do">## Define word-to-number mapping 5-point scale</span></span>
<span id="cb57-136"><a href="#cb57-136" aria-hidden="true" tabindex="-1"></a>likert5_recode <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb57-137"><a href="#cb57-137" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Strongly Disagree"</span> <span class="ot">=</span> <span class="dv">1</span>,</span>
<span id="cb57-138"><a href="#cb57-138" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Disagree"</span> <span class="ot">=</span> <span class="dv">2</span>,</span>
<span id="cb57-139"><a href="#cb57-139" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Neutral"</span> <span class="ot">=</span> <span class="dv">3</span>,</span>
<span id="cb57-140"><a href="#cb57-140" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Agree"</span> <span class="ot">=</span> <span class="dv">4</span>,</span>
<span id="cb57-141"><a href="#cb57-141" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Strongly Agree"</span> <span class="ot">=</span> <span class="dv">5</span></span>
<span id="cb57-142"><a href="#cb57-142" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb57-143"><a href="#cb57-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-144"><a href="#cb57-144" aria-hidden="true" tabindex="-1"></a><span class="do">## Convert text responses to numeric values</span></span>
<span id="cb57-145"><a href="#cb57-145" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb57-146"><a href="#cb57-146" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(</span>
<span id="cb57-147"><a href="#cb57-147" aria-hidden="true" tabindex="-1"></a>    <span class="at">.cols =</span> <span class="fu">contains</span>(<span class="st">"likert5"</span>), </span>
<span id="cb57-148"><a href="#cb57-148" aria-hidden="true" tabindex="-1"></a>    <span class="at">.fns =</span> <span class="sc">~</span> likert5_recode[.x]</span>
<span id="cb57-149"><a href="#cb57-149" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb57-150"><a href="#cb57-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-151"><a href="#cb57-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-152"><a href="#cb57-152" aria-hidden="true" tabindex="-1"></a><span class="co"># Reverse key items</span></span>
<span id="cb57-153"><a href="#cb57-153" aria-hidden="true" tabindex="-1"></a><span class="do">## Reverse key likert7 items</span></span>
<span id="cb57-154"><a href="#cb57-154" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb57-155"><a href="#cb57-155" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(</span>
<span id="cb57-156"><a href="#cb57-156" aria-hidden="true" tabindex="-1"></a>    <span class="at">.cols =</span> <span class="fu">ends_with</span>(<span class="st">"_likert7rev"</span>),</span>
<span id="cb57-157"><a href="#cb57-157" aria-hidden="true" tabindex="-1"></a>    <span class="at">.fns =</span> <span class="sc">~</span> (<span class="dv">7</span> <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">-</span> .x</span>
<span id="cb57-158"><a href="#cb57-158" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span></span>
<span id="cb57-159"><a href="#cb57-159" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename_with</span>(</span>
<span id="cb57-160"><a href="#cb57-160" aria-hidden="true" tabindex="-1"></a>    <span class="at">.fn =</span> <span class="sc">~</span> <span class="fu">str_replace</span>(.x, <span class="st">"_likert7rev"</span>, <span class="st">"_likert7"</span>),</span>
<span id="cb57-161"><a href="#cb57-161" aria-hidden="true" tabindex="-1"></a>    <span class="at">.cols =</span> <span class="fu">ends_with</span>(<span class="st">"_likert7rev"</span>)</span>
<span id="cb57-162"><a href="#cb57-162" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb57-163"><a href="#cb57-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-164"><a href="#cb57-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-165"><a href="#cb57-165" aria-hidden="true" tabindex="-1"></a><span class="do">## No likert5 items are reverse-keyed but if they were</span></span>
<span id="cb57-166"><a href="#cb57-166" aria-hidden="true" tabindex="-1"></a><span class="do">## You would adapt the code above replacing 8 (one higher than 7) to 6 (one higher than 5)</span></span>
<span id="cb57-167"><a href="#cb57-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-168"><a href="#cb57-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-169"><a href="#cb57-169" aria-hidden="true" tabindex="-1"></a><span class="co"># Create scale scores</span></span>
<span id="cb57-170"><a href="#cb57-170" aria-hidden="true" tabindex="-1"></a><span class="do">## mutate commands create scale scores</span></span>
<span id="cb57-171"><a href="#cb57-171" aria-hidden="true" tabindex="-1"></a><span class="do">## select commands with "-" remove items after scale creation</span></span>
<span id="cb57-172"><a href="#cb57-172" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span> </span>
<span id="cb57-173"><a href="#cb57-173" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb57-174"><a href="#cb57-174" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">affective_commitment =</span> <span class="fu">mean</span>(<span class="fu">c_across</span>(<span class="fu">starts_with</span>(<span class="st">"aff_com"</span>)),</span>
<span id="cb57-175"><a href="#cb57-175" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb57-176"><a href="#cb57-176" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">continuance_commitment =</span> <span class="fu">mean</span>(<span class="fu">c_across</span>(<span class="fu">starts_with</span>(<span class="st">"contin_com"</span>)),</span>
<span id="cb57-177"><a href="#cb57-177" aria-hidden="true" tabindex="-1"></a>                                       <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb57-178"><a href="#cb57-178" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">normative_commitment =</span> <span class="fu">mean</span>(<span class="fu">c_across</span>(<span class="fu">starts_with</span>(<span class="st">"norm_com"</span>)),</span>
<span id="cb57-179"><a href="#cb57-179" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb57-180"><a href="#cb57-180" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">job_satisfaction =</span> <span class="fu">mean</span>(<span class="fu">c_across</span>(<span class="fu">starts_with</span>(<span class="st">"job_aff"</span>)),</span>
<span id="cb57-181"><a href="#cb57-181" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb57-182"><a href="#cb57-182" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb57-183"><a href="#cb57-183" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">starts_with</span>(<span class="st">"aff_com"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb57-184"><a href="#cb57-184" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">starts_with</span>(<span class="st">"contin_com"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb57-185"><a href="#cb57-185" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">starts_with</span>(<span class="st">"norm_com"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb57-186"><a href="#cb57-186" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">starts_with</span>(<span class="st">"job_aff"</span>)) </span>
<span id="cb57-187"><a href="#cb57-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-188"><a href="#cb57-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-189"><a href="#cb57-189" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(analytic_data_survey)</span>
<span id="cb57-190"><a href="#cb57-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-191"><a href="#cb57-191" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb57-192"><a href="#cb57-192" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(duration_in_seconds <span class="sc">&gt;=</span> <span class="dv">120</span>)</span>
<span id="cb57-193"><a href="#cb57-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-194"><a href="#cb57-194" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(analytic_data_survey)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="extra-help" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="extra-help"><span class="header-section-number">2.6</span> Extra Help</h2>
<section id="qualtrics" class="level3" data-number="2.6.1">
<h3 data-number="2.6.1" class="anchored" data-anchor-id="qualtrics"><span class="header-section-number">2.6.1</span> Qualtrics</h3>
<ul>
<li><p>University of Guelph <a href="https://www.lib.uoguelph.ca/working-data/data-collection-surveys">Qualtrics Login page</a></p></li>
<li><p>University of Guelph <a href="https://www.lib.uoguelph.ca/working-data/data-collection-surveys/qualtrics-frequently-asked-questions">Qualtrics FAQ page</a></p></li>
</ul>
</section>
<section id="surveys" class="level3" data-number="2.6.2">
<h3 data-number="2.6.2" class="anchored" data-anchor-id="surveys"><span class="header-section-number">2.6.2</span> Surveys</h3>
<ul>
<li><p>Dillman Method book can be found <a href="https://www.amazon.ca/Internet-Phone-Mail-Mixed-Mode-Surveys/dp/1118456149/ref=sr_1_1?dchild=1&amp;keywords=dillman+method&amp;qid=1632496487&amp;sr=8-1">here</a></p></li>
<li><p>Duke University Survey <a href="https://dism.duke.edu/about/resources/help-topics/">site</a></p></li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-meyer1993commitment" class="csl-entry" role="listitem">
Meyer, John P, Natalie J Allen, and Catherine A Smith. 1993. <span>“Commitment to Organizations and Occupations: Extension and Test of a Three-Component Conceptualization.”</span> <em>Journal of Applied Psychology</em> 78 (4): 538.
</div>
<div id="ref-thompson2012brief" class="csl-entry" role="listitem">
Thompson, Edmund R, and Florence TT Phua. 2012. <span>“A Brief Index of Affective Job Satisfaction.”</span> <em>Group &amp; Organization Management</em> 37 (3): 275–307.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./workflow.html" class="pagination-link" aria-label="An Emphasis on Workflow">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">An Emphasis on Workflow</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./correlation.html" class="pagination-link" aria-label="Regression and correlation">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regression and correlation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>